// Code generated by cfprotobuf. DO NOT EDIT.

package testtypes

import (
	"encoding/binary"
	"math"

	cfprotobuf "github.com/centrifugal/protocol/cfprotobuf"
)

// SizeVT returns the size of the Protobuf encoding of m.
func (m *Empty) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	n += len(m.unknownFields)
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *Empty) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *Empty) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *Empty) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Empty) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *Empty) unmarshalVT(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeVT returns the size of the Protobuf encoding of m.
func (m *Leaf) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	if m.ID != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.ID)
	}
	if m.Text != "" {
		n += 1 + len(m.Text) + cfprotobuf.SizeOfLen(len(m.Text))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *Leaf) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *Leaf) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *Leaf) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Text != "" {
		i -= len(m.Text)
		copy(b[i:], m.Text)
		i = cfprotobuf.PutLen(b, i, len(m.Text))
		i--
		b[i] = 0x12
	}
	if m.ID != 0 {
		i = cfprotobuf.PutInt(b, i, m.ID)
		i--
		b[i] = 0x8
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Leaf) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *Leaf) unmarshalVT(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // ID
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.ID = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 2: // Text
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Text = string(s)
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeVT returns the size of the Protobuf encoding of m.
func (m *All) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	if m.String != "" {
		n += 1 + len(m.String) + cfprotobuf.SizeOfLen(len(m.String))
	}
	if len(m.Bytes) > 0 {
		n += 1 + len(m.Bytes) + cfprotobuf.SizeOfLen(len(m.Bytes))
	}
	if len(m.Raw) > 0 {
		n += 1 + len(m.Raw) + cfprotobuf.SizeOfLen(len(m.Raw))
	}
	if m.Bool {
		n += 1 + 1
	}
	if m.Int32 != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Int32)
	}
	if m.Int64 != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Int64)
	}
	if m.Uint32 != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Uint32)
	}
	if m.Uint64 != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.Uint64)
	}
	if m.Sint64 != 0 {
		n += 1 + cfprotobuf.SizeOfVarint(cfprotobuf.Zigzag(m.Sint64))
	}
	if m.Double != 0 {
		n += 1 + 8
	}
	if m.Float != 0 {
		n += 1 + 4
	}
	if m.Leaf != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Leaf.SizeVT())
	}
	if m.Self != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Self.SizeVT())
	}
	for _, e := range m.Leaves {
		n += 1 + cfprotobuf.SizeOfMessage(e.SizeVT())
	}
	for _, e := range m.Strings {
		n += 1 + len(e) + cfprotobuf.SizeOfLen(len(e))
	}
	if len(m.StrMap) > 0 {
		for k, v := range m.StrMap {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + len(v) + cfprotobuf.SizeOfLen(len(v))
			n += 2 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	if len(m.LeafMap) > 0 {
		for k, v := range m.LeafMap {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + cfprotobuf.SizeOfMessage(v.SizeVT())
			n += 2 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	if len(m.FloatMap) > 0 {
		for k := range m.FloatMap {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + 8
			n += 2 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	if len(m.IntMap) > 0 {
		for k, v := range m.IntMap {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + cfprotobuf.SizeOfInt(v)
			n += 2 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	if len(m.BoolMap) > 0 {
		for k := range m.BoolMap {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + 1
			n += 2 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	if m.Name != "" {
		n += 2 + len(m.Name) + cfprotobuf.SizeOfLen(len(m.Name))
	}
	if m.Level != 0 {
		n += 2 + cfprotobuf.SizeOfInt(m.Level)
	}
	if m.Far != "" {
		n += 2 + len(m.Far) + cfprotobuf.SizeOfLen(len(m.Far))
	}
	if m.Farther != 0 {
		n += 4 + cfprotobuf.SizeOfInt(m.Farther)
	}
	if m.Farthest != nil {
		n += 5 + cfprotobuf.SizeOfMessage(m.Farthest.SizeVT())
	}
	n += len(m.unknownFields)
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *All) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *All) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *All) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Farthest != nil {
		{
			size, err := m.Farthest.MarshalToSizedBufferVT(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0xf
		i--
		b[i] = 0xff
		i--
		b[i] = 0xff
		i--
		b[i] = 0xff
		i--
		b[i] = 0xfa
	}
	if m.Farther != 0 {
		i = cfprotobuf.PutInt(b, i, m.Farther)
		i--
		b[i] = 0x1
		i--
		b[i] = 0x92
		i--
		b[i] = 0xbe
		i--
		b[i] = 0x80
	}
	if m.Far != "" {
		i -= len(m.Far)
		copy(b[i:], m.Far)
		i = cfprotobuf.PutLen(b, i, len(m.Far))
		i--
		b[i] = 0x7f
		i--
		b[i] = 0xfa
	}
	if m.Level != 0 {
		i = cfprotobuf.PutInt(b, i, m.Level)
		i--
		b[i] = 0x1
		i--
		b[i] = 0xb0
	}
	if m.Name != "" {
		i -= len(m.Name)
		copy(b[i:], m.Name)
		i = cfprotobuf.PutLen(b, i, len(m.Name))
		i--
		b[i] = 0x1
		i--
		b[i] = 0xaa
	}
	if len(m.BoolMap) > 0 {
		for k, v := range m.BoolMap {
			end := i
			i--
			b[i] = 0
			if v {
				b[i] = 1
			}
			i--
			b[i] = 0x10
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x1
			i--
			b[i] = 0xa2
		}
	}
	if len(m.IntMap) > 0 {
		for k, v := range m.IntMap {
			end := i
			i = cfprotobuf.PutInt(b, i, v)
			i--
			b[i] = 0x10
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x1
			i--
			b[i] = 0x9a
		}
	}
	if len(m.FloatMap) > 0 {
		for k, v := range m.FloatMap {
			end := i
			i -= 8
			binary.LittleEndian.PutUint64(b[i:], math.Float64bits(v))
			i--
			b[i] = 0x11
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x1
			i--
			b[i] = 0x92
		}
	}
	if len(m.LeafMap) > 0 {
		for k, v := range m.LeafMap {
			end := i
			{
				size, err := v.MarshalToSizedBufferVT(b[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = cfprotobuf.PutLen(b, i, size)
			}
			i--
			b[i] = 0x12
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x1
			i--
			b[i] = 0x8a
		}
	}
	if len(m.StrMap) > 0 {
		for k, v := range m.StrMap {
			end := i
			i -= len(v)
			copy(b[i:], v)
			i = cfprotobuf.PutLen(b, i, len(v))
			i--
			b[i] = 0x12
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0x1
			i--
			b[i] = 0x82
		}
	}
	for n := len(m.Strings) - 1; n >= 0; n-- {
		i -= len(m.Strings[n])
		copy(b[i:], m.Strings[n])
		i = cfprotobuf.PutLen(b, i, len(m.Strings[n]))
		i--
		b[i] = 0x7a
	}
	for n := len(m.Leaves) - 1; n >= 0; n-- {
		{
			size, err := m.Leaves[n].MarshalToSizedBufferVT(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x72
	}
	if m.Self != nil {
		{
			size, err := m.Self.MarshalToSizedBufferVT(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x6a
	}
	if m.Leaf != nil {
		{
			size, err := m.Leaf.MarshalToSizedBufferVT(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0x62
	}
	if m.Float != 0 {
		i -= 4
		binary.LittleEndian.PutUint32(b[i:], math.Float32bits(m.Float))
		i--
		b[i] = 0x5d
	}
	if m.Double != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(b[i:], math.Float64bits(m.Double))
		i--
		b[i] = 0x51
	}
	if m.Sint64 != 0 {
		i = cfprotobuf.PutVarint(b, i, cfprotobuf.Zigzag(m.Sint64))
		i--
		b[i] = 0x48
	}
	if m.Uint64 != 0 {
		i = cfprotobuf.PutInt(b, i, m.Uint64)
		i--
		b[i] = 0x40
	}
	if m.Uint32 != 0 {
		i = cfprotobuf.PutInt(b, i, m.Uint32)
		i--
		b[i] = 0x38
	}
	if m.Int64 != 0 {
		i = cfprotobuf.PutInt(b, i, m.Int64)
		i--
		b[i] = 0x30
	}
	if m.Int32 != 0 {
		i = cfprotobuf.PutInt(b, i, m.Int32)
		i--
		b[i] = 0x28
	}
	if m.Bool {
		i--
		b[i] = 1
		i--
		b[i] = 0x20
	}
	if len(m.Raw) > 0 {
		i -= len(m.Raw)
		copy(b[i:], m.Raw)
		i = cfprotobuf.PutLen(b, i, len(m.Raw))
		i--
		b[i] = 0x1a
	}
	if len(m.Bytes) > 0 {
		i -= len(m.Bytes)
		copy(b[i:], m.Bytes)
		i = cfprotobuf.PutLen(b, i, len(m.Bytes))
		i--
		b[i] = 0x12
	}
	if m.String != "" {
		i -= len(m.String)
		copy(b[i:], m.String)
		i = cfprotobuf.PutLen(b, i, len(m.String))
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *All) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *All) unmarshalVT(b []byte, depth int) error {
	depth++
	if depth > cfprotobuf.MaxDepth {
		return cfprotobuf.ErrTooDeep
	}
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		switch tag >> 3 {
		case 1: // String
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.String = string(s)
				i = to
				continue
			}
		case 2: // Bytes
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Bytes = append(m.Bytes[:0], b[from:to]...)
				if m.Bytes == nil {
					m.Bytes = []byte{}
				}
				i = to
				continue
			}
		case 3: // Raw
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				m.Raw = append(m.Raw[:0], b[from:to]...)
				if m.Raw == nil {
					m.Raw = Raw{}
				}
				i = to
				continue
			}
		case 4: // Bool
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Bool = v != 0
				i = next
				continue
			}
		case 5: // Int32
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Int32 = cfprotobuf.Int[int32](v)
				i = next
				continue
			}
		case 6: // Int64
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Int64 = cfprotobuf.Int[int64](v)
				i = next
				continue
			}
		case 7: // Uint32
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Uint32 = cfprotobuf.Int[uint32](v)
				i = next
				continue
			}
		case 8: // Uint64
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Uint64 = cfprotobuf.Int[uint64](v)
				i = next
				continue
			}
		case 9: // Sint64
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Sint64 = cfprotobuf.Unzigzag(v)
				i = next
				continue
			}
		case 10: // Double
			if tag&7 == 1 {
				if len(b)-i < 8 {
					return cfprotobuf.ErrTruncated
				}
				m.Double = math.Float64frombits(binary.LittleEndian.Uint64(b[i:]))
				i += 8
				continue
			}
		case 11: // Float
			if tag&7 == 5 {
				if len(b)-i < 4 {
					return cfprotobuf.ErrTruncated
				}
				m.Float = math.Float32frombits(binary.LittleEndian.Uint32(b[i:]))
				i += 4
				continue
			}
		case 12: // Leaf
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Leaf == nil {
					m.Leaf = new(Leaf)
				}
				if err := m.Leaf.unmarshalVT(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 13: // Self
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Self == nil {
					m.Self = new(All)
				}
				if err := m.Self.unmarshalVT(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		case 14: // Leaves
			if tag&7 == 2 {
				e := new(Leaf)
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if err := e.unmarshalVT(b[from:to], depth); err != nil {
					return err
				}
				i = to
				m.Leaves = append(m.Leaves, e)
				continue
			}
		case 15: // Strings
			if tag&7 == 2 {
				var e string
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				e = string(s)
				i = to
				m.Strings = append(m.Strings, e)
				continue
			}
		case 16: // StrMap
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.StrMap == nil {
					m.StrMap = make(map[string]string)
				}
				entry := b[from:to]
				var key string
				var val string
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = string(sKey)
						j = toKey
					case 18:
						fromVal := j + 1
						var toVal int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromVal {
							toVal = fromVal + int(entry[j])
						} else if fromVal, toVal = cfprotobuf.Length(entry, j); fromVal < 0 {
							return cfprotobuf.Error(fromVal)
						}
						sVal := entry[fromVal:toVal]
						if !cfprotobuf.ShortASCII(sVal) && !cfprotobuf.ValidString(sVal) {
							return cfprotobuf.ErrInvalidUTF8
						}
						val = string(sVal)
						j = toVal
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.StrMap[key] = val
				i = to
				continue
			}
		case 17: // LeafMap
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.LeafMap == nil {
					m.LeafMap = make(map[string]*Leaf)
				}
				entry := b[from:to]
				var key string
				val := new(Leaf)
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = string(sKey)
						j = toKey
					case 18:
						fromVal := j + 1
						var toVal int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromVal {
							toVal = fromVal + int(entry[j])
						} else if fromVal, toVal = cfprotobuf.Length(entry, j); fromVal < 0 {
							return cfprotobuf.Error(fromVal)
						}
						if err := val.unmarshalVT(entry[fromVal:toVal], depth); err != nil {
							return err
						}
						j = toVal
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.LeafMap[key] = val
				i = to
				continue
			}
		case 18: // FloatMap
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.FloatMap == nil {
					m.FloatMap = make(map[string]float64)
				}
				entry := b[from:to]
				var key string
				var val float64
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = string(sKey)
						j = toKey
					case 17:
						if len(entry)-j < 8 {
							return cfprotobuf.ErrTruncated
						}
						val = math.Float64frombits(binary.LittleEndian.Uint64(entry[j:]))
						j += 8
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.FloatMap[key] = val
				i = to
				continue
			}
		case 19: // IntMap
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.IntMap == nil {
					m.IntMap = make(map[string]int64)
				}
				entry := b[from:to]
				var key string
				var val int64
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = string(sKey)
						j = toKey
					case 16:
						var vVal uint64
						if j < len(entry) && entry[j] < 0x80 {
							vVal, next = uint64(entry[j]), j+1
						} else if vVal, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
						val = cfprotobuf.Int[int64](vVal)
						j = next
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.IntMap[key] = val
				i = to
				continue
			}
		case 20: // BoolMap
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.BoolMap == nil {
					m.BoolMap = make(map[Name]bool)
				}
				entry := b[from:to]
				var key Name
				var val bool
				for j := 0; j < len(entry); {
					entryTag := uint64(entry[j])
					next = j + 1
					if entryTag >= 0x80 {
						if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
					}
					j = next
					switch entryTag {
					case 10:
						fromKey := j + 1
						var toKey int
						if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
							toKey = fromKey + int(entry[j])
						} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
							return cfprotobuf.Error(fromKey)
						}
						sKey := entry[fromKey:toKey]
						if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
							return cfprotobuf.ErrInvalidUTF8
						}
						key = Name(sKey)
						j = toKey
					case 16:
						var vVal uint64
						if j < len(entry) && entry[j] < 0x80 {
							vVal, next = uint64(entry[j]), j+1
						} else if vVal, next = cfprotobuf.Varint(entry, j); next < 0 {
							return cfprotobuf.Error(next)
						}
						val = vVal != 0
						j = next
					default:
						next = cfprotobuf.Skip(entry, j, entryTag)
						if next < 0 {
							return cfprotobuf.Error(next)
						}
						j = next
					}
				}
				m.BoolMap[key] = val
				i = to
				continue
			}
		case 21: // Name
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Name = Name(s)
				i = to
				continue
			}
		case 22: // Level
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Level = cfprotobuf.Int[Level](v)
				i = next
				continue
			}
		case 2047: // Far
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				s := b[from:to]
				if !cfprotobuf.ShortASCII(s) && !cfprotobuf.ValidString(s) {
					return cfprotobuf.ErrInvalidUTF8
				}
				m.Far = string(s)
				i = to
				continue
			}
		case 300000: // Farther
			if tag&7 == 0 {
				var v uint64
				if i < len(b) && b[i] < 0x80 {
					v, next = uint64(b[i]), i+1
				} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
					return cfprotobuf.Error(next)
				}
				m.Farther = cfprotobuf.Int[uint64](v)
				i = next
				continue
			}
		case 536870911: // Farthest
			if tag&7 == 2 {
				from := i + 1
				var to int
				if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
					to = from + int(b[i])
				} else if from, to = cfprotobuf.Length(b, i); from < 0 {
					return cfprotobuf.Error(from)
				}
				if m.Farthest == nil {
					m.Farthest = new(Leaf)
				}
				if err := m.Farthest.unmarshalVT(b[from:to], depth); err != nil {
					return err
				}
				i = to
				continue
			}
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		m.unknownFields = cfprotobuf.AppendUnknown(m.unknownFields, tag, b[i:next])
		i = next
	}
	return nil
}

// SizeVT returns the size of the Protobuf encoding of m.
func (m *NoUnknown) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	if m.ID != 0 {
		n += 1 + cfprotobuf.SizeOfInt(m.ID)
	}
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *NoUnknown) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *NoUnknown) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *NoUnknown) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.ID != 0 {
		i = cfprotobuf.PutInt(b, i, m.ID)
		i--
		b[i] = 0x8
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *NoUnknown) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *NoUnknown) unmarshalVT(b []byte, depth int) error {
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		if tag == 8 { // ID
			var v uint64
			if i < len(b) && b[i] < 0x80 {
				v, next = uint64(b[i]), i+1
			} else if v, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
			m.ID = cfprotobuf.Int[uint32](v)
			i = next
			continue
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		i = next
	}
	return nil
}

// SizeVT returns the size of the Protobuf encoding of m.
func (m *Ping) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	if m.Pong != nil {
		n += 1 + cfprotobuf.SizeOfMessage(m.Pong.SizeVT())
	}
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *Ping) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *Ping) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *Ping) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if m.Pong != nil {
		{
			size, err := m.Pong.MarshalToSizedBufferVT(b[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = cfprotobuf.PutLen(b, i, size)
		}
		i--
		b[i] = 0xa
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Ping) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *Ping) unmarshalVT(b []byte, depth int) error {
	depth++
	if depth > cfprotobuf.MaxDepth {
		return cfprotobuf.ErrTooDeep
	}
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		if tag == 10 { // Pong
			from := i + 1
			var to int
			if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
				to = from + int(b[i])
			} else if from, to = cfprotobuf.Length(b, i); from < 0 {
				return cfprotobuf.Error(from)
			}
			if m.Pong == nil {
				m.Pong = new(Pong)
			}
			if err := m.Pong.unmarshalVT(b[from:to], depth); err != nil {
				return err
			}
			i = to
			continue
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		i = next
	}
	return nil
}

// SizeVT returns the size of the Protobuf encoding of m.
func (m *Pong) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Pings) > 0 {
		for k, v := range m.Pings {
			entry := 1 + len(k) + cfprotobuf.SizeOfLen(len(k)) + 1 + cfprotobuf.SizeOfMessage(v.SizeVT())
			n += 1 + entry + cfprotobuf.SizeOfLen(entry)
		}
	}
	return n
}

// MarshalVT returns the Protobuf encoding of m.
func (m *Pong) MarshalVT() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	b := make([]byte, m.SizeVT())
	n, err := m.MarshalToSizedBufferVT(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

// MarshalToVT writes the Protobuf encoding of m to the beginning of b, which must
// have room for SizeVT bytes, and returns the number of bytes written.
func (m *Pong) MarshalToVT(b []byte) (int, error) {
	return m.MarshalToSizedBufferVT(b[:m.SizeVT()])
}

// MarshalToSizedBufferVT writes the Protobuf encoding of m to the end of b, which
// must have room for SizeVT bytes, and returns the number of bytes written.
func (m *Pong) MarshalToSizedBufferVT(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.Pings) > 0 {
		for k, v := range m.Pings {
			end := i
			{
				size, err := v.MarshalToSizedBufferVT(b[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = cfprotobuf.PutLen(b, i, size)
			}
			i--
			b[i] = 0x12
			i -= len(k)
			copy(b[i:], k)
			i = cfprotobuf.PutLen(b, i, len(k))
			i--
			b[i] = 0xa
			i = cfprotobuf.PutLen(b, i, end-i)
			i--
			b[i] = 0xa
		}
	}
	return len(b) - i, nil
}

// UnmarshalVT decodes the Protobuf encoding of a message from b into m. Fields
// which are not in b are left as they are. Everything decoded is copied out of
// b, which may be reused afterwards.
func (m *Pong) UnmarshalVT(b []byte) error {
	return m.unmarshalVT(b, 0)
}

func (m *Pong) unmarshalVT(b []byte, depth int) error {
	depth++
	if depth > cfprotobuf.MaxDepth {
		return cfprotobuf.ErrTooDeep
	}
	for i := 0; i < len(b); {
		tag, next := uint64(b[i]), i+1
		if tag >= 0x80 {
			if tag, next = cfprotobuf.Varint(b, i); next < 0 {
				return cfprotobuf.Error(next)
			}
		}
		i = next
		if tag == 10 { // Pings
			from := i + 1
			var to int
			if i < len(b) && b[i] < 0x80 && int(b[i]) <= len(b)-from {
				to = from + int(b[i])
			} else if from, to = cfprotobuf.Length(b, i); from < 0 {
				return cfprotobuf.Error(from)
			}
			if m.Pings == nil {
				m.Pings = make(map[string]*Ping)
			}
			entry := b[from:to]
			var key string
			val := new(Ping)
			for j := 0; j < len(entry); {
				entryTag := uint64(entry[j])
				next = j + 1
				if entryTag >= 0x80 {
					if entryTag, next = cfprotobuf.Varint(entry, j); next < 0 {
						return cfprotobuf.Error(next)
					}
				}
				j = next
				switch entryTag {
				case 10:
					fromKey := j + 1
					var toKey int
					if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromKey {
						toKey = fromKey + int(entry[j])
					} else if fromKey, toKey = cfprotobuf.Length(entry, j); fromKey < 0 {
						return cfprotobuf.Error(fromKey)
					}
					sKey := entry[fromKey:toKey]
					if !cfprotobuf.ShortASCII(sKey) && !cfprotobuf.ValidString(sKey) {
						return cfprotobuf.ErrInvalidUTF8
					}
					key = string(sKey)
					j = toKey
				case 18:
					fromVal := j + 1
					var toVal int
					if j < len(entry) && entry[j] < 0x80 && int(entry[j]) <= len(entry)-fromVal {
						toVal = fromVal + int(entry[j])
					} else if fromVal, toVal = cfprotobuf.Length(entry, j); fromVal < 0 {
						return cfprotobuf.Error(fromVal)
					}
					if err := val.unmarshalVT(entry[fromVal:toVal], depth); err != nil {
						return err
					}
					j = toVal
				default:
					next = cfprotobuf.Skip(entry, j, entryTag)
					if next < 0 {
						return cfprotobuf.Error(next)
					}
					j = next
				}
			}
			m.Pings[key] = val
			i = to
			continue
		}
		next = cfprotobuf.Skip(b, i, tag)
		if next < 0 {
			return cfprotobuf.Error(next)
		}
		i = next
	}
	return nil
}
