#!/bin/bash
#
# Regenerates ../../cfjson/BENCHMARKS.md from the raw benchmark output in
# results/. Run it through `make json-bench-doc` in the repository root.
#
# results/<machine>.txt           - output of the benchmarks of this module
#                                   (`make json-bench` writes bench.txt, move it
#                                   there under the name of the machine);
# results/<machine>.before.txt,
# results/<machine>.after.txt     - the protocol benchmarks with type=json of
#                                   bench.ref.txt and bench.head.txt written by
#                                   `make bench-compare REF=v0.22.1`.
#
# Requires benchstat: go install golang.org/x/perf/cmd/benchstat@latest

set -euo pipefail

cd "$(dirname "$0")"

if ! command -v benchstat >/dev/null 2>&1; then
  echo "error: benchstat not found in PATH" >&2
  exit 1
fi

out=../../cfjson/BENCHMARKS.md

# table FILE FILTER UNIT prints one benchstat table (sec/op or allocs/op) with
# implementations as columns and messages as rows.
table() {
  echo '```'
  # A table starts with the line naming the implementations, followed by the
  # line naming the unit, and ends with an empty line.
  benchstat -filter "$2" -col /impl -row /msg "$1" 2>/dev/null |
    awk -v unit="$3" '
      done { next }
      !found && index($0, unit) { found = 1; print prev }
      found && /^ *$/ { done = 1; next }
      found { print }
      { prev = $0 }
    ' | sed -e 's/ *$//'
  echo '```'
}

{
  cat <<'HEADER'
# Benchmarks

cfjson against what it replaced in `github.com/centrifugal/protocol`:
[easyjson](https://github.com/mailru/easyjson) for encoding and
[segmentio/encoding](https://github.com/segmentio/encoding) for decoding and
validation.

This file is generated by `make json-bench-doc` from the raw output kept in
[internal/cfjsoncmp/results](../internal/cfjsoncmp/results). The benchmarks
live in [internal/cfjsoncmp](../internal/cfjsoncmp), a module which has both
implementations as methods of the very same struct types, so both do the same
work on the same values. The tables are `benchstat` output: 10 samples per
benchmark, the first column is the old implementation, `vs base` is the change
relative to it.

The messages:

| Name | What it is |
| --- | --- |
| `cmd_ping` | An empty command, `{}`. |
| `cmd_connect` | Connect command with a JWT and one server-side subscription. |
| `cmd_subscribe` | Subscribe command with a JWT and recovery position. |
| `cmd_publish_256`, `cmd_publish_4k` | Publish command, the payload is one string of that size. |
| `cmd_publish_doc_1k` | Publish command, the payload is about 1 KiB of nested objects, arrays, numbers and short strings. |
| `cmd_publish_utf8_1k` | Publish command, the payload is about 1 KiB of text outside of ASCII (Cyrillic and emoji). cfjson checks that it is valid UTF-8, segmentio does not. |
| `cmd_rpc` | RPC command with a small payload. |
| `reply_pub_256`, `reply_pub_4k`, `reply_pub_doc_1k`, `reply_pub_utf8_1k` | A publication pushed to a subscriber, payloads as above. |
| `reply_pub_info_256` | The same with client info and tags. |
| `reply_join` | A join push. |
| `reply_connect` | Connect reply with one subscription. |
| `reply_subscribe_recovered_20` | Subscribe reply with 20 recovered publications. |
| `reply_history_100` | History reply with 100 publications. |
| `reply_presence_100` | Presence reply with 100 clients. |
| `reply_error` | An error reply. |

How to read the sections:

- **Encode** is encoding the way `protocol` does it: into a pooled buffer,
  with the result copied into a slice of its own. The old implementation is
  easyjson writing into the custom writer `protocol` had.
- **Encode, codec only** writes into a buffer which is reused, leaving only
  the generated code to compare.
- **Decode** is decoding into a new message. `segmentio` is what `protocol`
  used. `easyjson` is the decoder easyjson generates, which `protocol` never
  used; it is there because cfjson replaces easyjson as the generator. All
  of them copy strings out of the input.
- **Decode, codec only** decodes into the same message over and over, so
  that there is little besides strings to allocate. `protocol`
  never decodes this way. segmentio decodes into the elements a slice already
  has, where cfjson allocates new ones so that fields of a previous message
  cannot leak into the next: that is why cfjson is behind for the two replies
  with many publications here, and only here.
- **Validate** is checking that an encoded message is valid JSON, which
  `protocol` did for every Reply and Push it encoded; it checks the payloads
  of a message only now.
- **protocol before and after** are the benchmarks of the `protocol`
  package itself (`bench_test.go` in the repository root, `type=json`), run
  against v0.22.1, the last release before the switch to cfjson, and against
  this branch: `make bench-compare REF=v0.22.1` in the repository root.
HEADER

  for file in results/*.txt; do
    case "$file" in
    *.before.txt | *.after.txt) continue ;;
    esac
    machine=$(basename "$file" .txt)
    echo
    echo "## $machine"
    echo
    echo '```'
    grep -E '^(goos|goarch|cpu):' "$file" | sort -u
    echo '```'

    echo
    echo "### Encode"
    echo
    table "$file" ".name:Encode" "sec/op"
    echo
    echo "Allocations:"
    echo
    table "$file" ".name:Encode" "allocs/op"

    echo
    echo "### Encode, codec only"
    echo
    table "$file" ".name:Append" "sec/op"

    echo
    echo "### Decode, copying"
    echo
    table "$file" ".name:Decode /mode:copy" "sec/op"
    echo
    echo "Allocations:"
    echo
    table "$file" ".name:Decode /mode:copy" "allocs/op"


    echo
    echo "### Decode, codec only"
    echo
    table "$file" ".name:DecodeReuse" "sec/op"

    echo
    echo "### Validate"
    echo
    table "$file" ".name:Valid" "sec/op"

    before="results/$machine.before.txt"
    after="results/$machine.after.txt"
    if [[ -f "$before" && -f "$after" ]]; then
      echo
      echo "### protocol before and after"
      echo
      echo '```'
      benchstat "before=$before" "after=$after" 2>/dev/null | sed -e 's/ *$//' | grep -v '^\(goos\|goarch\|pkg\|cpu\):'
      echo '```'
    fi
  done
} >"$out"

echo "wrote $out"
