// Code generated by cfjson. DO NOT EDIT.

package foreign

import (
	ext "github.com/centrifugal/protocol/cfjson/internal/testtypes/foreign/ext"
	time "time"

	cfjson "github.com/centrifugal/protocol/cfjson"
)

// AppendJSON appends the JSON encoding of m to b.
func (m *ConnectClaims) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.ExpireAt != nil {
		b = append(b, ",\"expire_at\":"...)
		b = cfjson.AppendInt(b, (*m.ExpireAt))
	}
	if len(m.Info) != 0 {
		b = append(b, ",\"info\":"...)
		b = cfjson.AppendRaw(b, m.Info)
	}
	if len(m.Channels) != 0 {
		b = append(b, ",\"channels\":"...)
		b = append(b, '[')
		for n1, e2 := range m.Channels {
			if n1 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e2)
		}
		b = append(b, ']')
	}
	if len(m.Subs) != 0 {
		b = append(b, ",\"subs\":"...)
		s3 := len(b)
		for k4, e5 := range m.Subs {
			b = append(b, ',')
			b = cfjson.AppendString(b, k4)
			b = append(b, ':')
			b = e5.AppendJSON(b)
		}
		b[s3] = '{'
		b = append(b, '}')
	}
	if len(m.Meta) != 0 {
		b = append(b, ",\"meta\":"...)
		b = cfjson.AppendRaw(b, m.Meta)
	}
	if len(m.Caps) != 0 {
		b = append(b, ",\"caps\":"...)
		b = append(b, '[')
		for n6, e7 := range m.Caps {
			if n6 != 0 {
				b = append(b, ',')
			}
			if e7 == nil {
				b = append(b, "null"...)
			} else {
				b = appendJSONExtCapability(b, e7)
			}
		}
		b = append(b, ']')
	}
	b = append(b, ",\"cap\":"...)
	b = appendJSONExtCapability(b, &m.Cap)
	if len(m.Labels) != 0 {
		b = append(b, ",\"labels\":"...)
		s8 := len(b)
		for k9, e10 := range m.Labels {
			b = append(b, ',')
			b = cfjson.AppendString(b, k9)
			b = append(b, ':')
			b = cfjson.AppendString(b, e10)
		}
		b[s8] = '{'
		b = append(b, '}')
	}
	if m.Channel != "" {
		b = append(b, ",\"channel\":"...)
		b = cfjson.AppendString(b, m.Channel)
	}
	b = append(b, ",\"seen\":"...)
	b = cfjson.AppendMarshaler(b, &m.Seen)
	if m.Until != nil {
		b = append(b, ",\"until\":"...)
		b = cfjson.AppendMarshaler(b, m.Until)
	}
	if m.RegisteredClaims.Issuer != "" {
		b = append(b, ",\"iss\":"...)
		b = cfjson.AppendString(b, m.RegisteredClaims.Issuer)
	}
	if m.RegisteredClaims.Subject != "" {
		b = append(b, ",\"sub\":"...)
		b = cfjson.AppendString(b, m.RegisteredClaims.Subject)
	}
	if len(m.RegisteredClaims.Audience) != 0 {
		b = append(b, ",\"aud\":"...)
		b = cfjson.AppendMarshaler(b, &m.RegisteredClaims.Audience)
	}
	if m.RegisteredClaims.ExpiresAt != nil {
		b = append(b, ",\"exp\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.ExpiresAt)
	}
	if m.RegisteredClaims.NotBefore != nil {
		b = append(b, ",\"nbf\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.NotBefore)
	}
	if m.RegisteredClaims.IssuedAt != nil {
		b = append(b, ",\"iat\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.IssuedAt)
	}
	if m.RegisteredClaims.ID != "" {
		b = append(b, ",\"jti\":"...)
		b = cfjson.AppendString(b, m.RegisteredClaims.ID)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *ConnectClaims) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"expire_at\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+12)
			}
		case 1:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"info\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+7)
			}
		case 2:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"channels\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+11)
			}
		case 3:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"subs\":" {
				id = 3
				i = cfjson.SkipSpace(b, i+7)
			}
		case 4:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"meta\":" {
				id = 4
				i = cfjson.SkipSpace(b, i+7)
			}
		case 5:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"caps\":" {
				id = 5
				i = cfjson.SkipSpace(b, i+7)
			}
		case 6:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"cap\":" {
				id = 6
				i = cfjson.SkipSpace(b, i+6)
			}
		case 7:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"labels\":" {
				id = 7
				i = cfjson.SkipSpace(b, i+9)
			}
		case 8:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"channel\":" {
				id = 8
				i = cfjson.SkipSpace(b, i+10)
			}
		case 9:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"seen\":" {
				id = 9
				i = cfjson.SkipSpace(b, i+7)
			}
		case 10:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"until\":" {
				id = 10
				i = cfjson.SkipSpace(b, i+8)
			}
		case 11:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"iss\":" {
				id = 11
				i = cfjson.SkipSpace(b, i+6)
			}
		case 12:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"sub\":" {
				id = 12
				i = cfjson.SkipSpace(b, i+6)
			}
		case 13:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"aud\":" {
				id = 13
				i = cfjson.SkipSpace(b, i+6)
			}
		case 14:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"exp\":" {
				id = 14
				i = cfjson.SkipSpace(b, i+6)
			}
		case 15:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"nbf\":" {
				id = 15
				i = cfjson.SkipSpace(b, i+6)
			}
		case 16:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"iat\":" {
				id = 16
				i = cfjson.SkipSpace(b, i+6)
			}
		case 17:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"jti\":" {
				id = 17
				i = cfjson.SkipSpace(b, i+6)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "expire_at":
				id = 0
			case "info":
				id = 1
			case "channels":
				id = 2
			case "subs":
				id = 3
			case "meta":
				id = 4
			case "caps":
				id = 5
			case "cap":
				id = 6
			case "labels":
				id = 7
			case "channel":
				id = 8
			case "seen":
				id = 9
			case "until":
				id = 10
			case "iss":
				id = 11
			case "sub":
				id = 12
			case "aud":
				id = 13
			case "exp":
				id = 14
			case "nbf":
				id = 15
			case "iat":
				id = 16
			case "jti":
				id = 17
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			if cfjson.IsNull(b, i) {
				m.ExpireAt = nil
				i += 4
			} else {
				if m.ExpireAt == nil {
					m.ExpireAt = new(int64)
				}
				i = cfjson.Int(b, i, m.ExpireAt)
			}
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Info))
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			if cfjson.IsNull(b, i) {
				m.Channels = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Channels == nil {
						m.Channels = []string{}
					} else {
						m.Channels = m.Channels[:0]
					}
				} else {
					if cap(m.Channels) == 0 {
						m.Channels = make([]string, 0, 10)
					} else {
						m.Channels = m.Channels[:0]
					}
					for {
						var e1 string
						i = cfjson.String(b, i, f, &e1)
						if i < 0 {
							return i
						}
						m.Channels = append(m.Channels, e1)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 3
		case 3:
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			if cfjson.IsNull(b, i) {
				m.Subs = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.Subs = make(map[string]SubscribeOptions)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n4 := 0
					for {
						var k2 string
						i = cfjson.MapKey(b, i, f, &k2)
						if i < 0 {
							return i
						}
						var e3 SubscribeOptions
						i = e3.DecodeJSON(b, i, f)
						if i < 0 {
							return i
						}
						m.Subs[k2] = e3
						n4++
						if len(m.Subs) != n4 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 4
		case 4:
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Meta))
			next = 5
		case 5:
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			if cfjson.IsNull(b, i) {
				m.Caps = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Caps == nil {
						m.Caps = []*ext.Capability{}
					} else {
						m.Caps = m.Caps[:0]
					}
				} else {
					if cap(m.Caps) == 0 {
						m.Caps = make([]*ext.Capability, 0, 10)
					} else {
						m.Caps = m.Caps[:0]
					}
					for {
						var e5 *ext.Capability
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e5 = new(ext.Capability)
							i = decodeJSONExtCapability(e5, b, i, f)
						}
						if i < 0 {
							return i
						}
						m.Caps = append(m.Caps, e5)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 6
		case 6:
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = decodeJSONExtCapability(&m.Cap, b, i, f)
			next = 7
		case 7:
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			if cfjson.IsNull(b, i) {
				m.Labels = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.Labels = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n8 := 0
					for {
						var k6 string
						i = cfjson.MapKey(b, i, f, &k6)
						if i < 0 {
							return i
						}
						var e7 string
						i = cfjson.String(b, i, f, &e7)
						if i < 0 {
							return i
						}
						m.Labels[k6] = e7
						n8++
						if len(m.Labels) != n8 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 8
		case 8:
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			i = cfjson.String(b, i, f, &m.Channel)
			next = 9
		case 9:
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			i = cfjson.DecodeUnmarshaler(b, i, f, &m.Seen)
			next = 10
		case 10:
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			if cfjson.IsNull(b, i) {
				m.Until = nil
				i += 4
			} else {
				if m.Until == nil {
					m.Until = new(time.Time)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.Until)
			}
			next = 11
		case 11:
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			i = cfjson.String(b, i, f, &m.RegisteredClaims.Issuer)
			next = 12
		case 12:
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			i = cfjson.String(b, i, f, &m.RegisteredClaims.Subject)
			next = 13
		case 13:
			if seen0&0x2000 != 0 {
				return ^i
			}
			seen0 |= 0x2000
			i = cfjson.DecodeUnmarshaler(b, i, f, &m.RegisteredClaims.Audience)
			next = 14
		case 14:
			if seen0&0x4000 != 0 {
				return ^i
			}
			seen0 |= 0x4000
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.ExpiresAt = nil
				i += 4
			} else {
				if m.RegisteredClaims.ExpiresAt == nil {
					m.RegisteredClaims.ExpiresAt = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.ExpiresAt)
			}
			next = 15
		case 15:
			if seen0&0x8000 != 0 {
				return ^i
			}
			seen0 |= 0x8000
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.NotBefore = nil
				i += 4
			} else {
				if m.RegisteredClaims.NotBefore == nil {
					m.RegisteredClaims.NotBefore = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.NotBefore)
			}
			next = 16
		case 16:
			if seen0&0x10000 != 0 {
				return ^i
			}
			seen0 |= 0x10000
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.IssuedAt = nil
				i += 4
			} else {
				if m.RegisteredClaims.IssuedAt == nil {
					m.RegisteredClaims.IssuedAt = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.IssuedAt)
			}
			next = 17
		case 17:
			if seen0&0x20000 != 0 {
				return ^i
			}
			seen0 |= 0x20000
			i = cfjson.String(b, i, f, &m.RegisteredClaims.ID)
			next = 18
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *SubscribeClaims) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.RegisteredClaims.Issuer != "" {
		b = append(b, ",\"iss\":"...)
		b = cfjson.AppendString(b, m.RegisteredClaims.Issuer)
	}
	if len(m.RegisteredClaims.Audience) != 0 {
		b = append(b, ",\"aud\":"...)
		b = cfjson.AppendMarshaler(b, &m.RegisteredClaims.Audience)
	}
	if m.RegisteredClaims.ExpiresAt != nil {
		b = append(b, ",\"exp\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.ExpiresAt)
	}
	if m.RegisteredClaims.NotBefore != nil {
		b = append(b, ",\"nbf\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.NotBefore)
	}
	if m.RegisteredClaims.IssuedAt != nil {
		b = append(b, ",\"iat\":"...)
		b = cfjson.AppendMarshaler(b, m.RegisteredClaims.IssuedAt)
	}
	if m.RegisteredClaims.ID != "" {
		b = append(b, ",\"jti\":"...)
		b = cfjson.AppendString(b, m.RegisteredClaims.ID)
	}
	if len(m.SubscribeOptions.Info) != 0 {
		b = append(b, ",\"info\":"...)
		b = cfjson.AppendRaw(b, m.SubscribeOptions.Info)
	}
	if m.SubscribeOptions.Presence {
		b = append(b, ",\"presence\":true"...)
	}
	if m.SubscribeOptions.ExpireAt != nil {
		b = append(b, ",\"expire_at\":"...)
		b = cfjson.AppendInt(b, (*m.SubscribeOptions.ExpireAt))
	}
	if m.Extra != nil && m.Extra.Note != "" {
		b = append(b, ",\"note\":"...)
		b = cfjson.AppendString(b, m.Extra.Note)
	}
	if m.Extra != nil && m.Extra.Shard != 0 {
		b = append(b, ",\"shard\":"...)
		b = cfjson.AppendInt(b, int64(m.Extra.Shard))
	}
	if m.Channel != "" {
		b = append(b, ",\"channel\":"...)
		b = cfjson.AppendString(b, m.Channel)
	}
	if m.Subject != "" {
		b = append(b, ",\"sub\":"...)
		b = cfjson.AppendString(b, m.Subject)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *SubscribeClaims) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"iss\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+6)
			}
		case 1:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"aud\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+6)
			}
		case 2:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"exp\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+6)
			}
		case 3:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"nbf\":" {
				id = 3
				i = cfjson.SkipSpace(b, i+6)
			}
		case 4:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"iat\":" {
				id = 4
				i = cfjson.SkipSpace(b, i+6)
			}
		case 5:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"jti\":" {
				id = 5
				i = cfjson.SkipSpace(b, i+6)
			}
		case 6:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"info\":" {
				id = 6
				i = cfjson.SkipSpace(b, i+7)
			}
		case 7:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"presence\":" {
				id = 7
				i = cfjson.SkipSpace(b, i+11)
			}
		case 8:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"expire_at\":" {
				id = 8
				i = cfjson.SkipSpace(b, i+12)
			}
		case 9:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"note\":" {
				id = 9
				i = cfjson.SkipSpace(b, i+7)
			}
		case 10:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"shard\":" {
				id = 10
				i = cfjson.SkipSpace(b, i+8)
			}
		case 11:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"channel\":" {
				id = 11
				i = cfjson.SkipSpace(b, i+10)
			}
		case 12:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"sub\":" {
				id = 12
				i = cfjson.SkipSpace(b, i+6)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "iss":
				id = 0
			case "aud":
				id = 1
			case "exp":
				id = 2
			case "nbf":
				id = 3
			case "iat":
				id = 4
			case "jti":
				id = 5
			case "info":
				id = 6
			case "presence":
				id = 7
			case "expire_at":
				id = 8
			case "note":
				id = 9
			case "shard":
				id = 10
			case "channel":
				id = 11
			case "sub":
				id = 12
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.RegisteredClaims.Issuer)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.DecodeUnmarshaler(b, i, f, &m.RegisteredClaims.Audience)
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.ExpiresAt = nil
				i += 4
			} else {
				if m.RegisteredClaims.ExpiresAt == nil {
					m.RegisteredClaims.ExpiresAt = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.ExpiresAt)
			}
			next = 3
		case 3:
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.NotBefore = nil
				i += 4
			} else {
				if m.RegisteredClaims.NotBefore == nil {
					m.RegisteredClaims.NotBefore = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.NotBefore)
			}
			next = 4
		case 4:
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			if cfjson.IsNull(b, i) {
				m.RegisteredClaims.IssuedAt = nil
				i += 4
			} else {
				if m.RegisteredClaims.IssuedAt == nil {
					m.RegisteredClaims.IssuedAt = new(ext.NumericDate)
				}
				i = cfjson.DecodeUnmarshaler(b, i, f, m.RegisteredClaims.IssuedAt)
			}
			next = 5
		case 5:
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			i = cfjson.String(b, i, f, &m.RegisteredClaims.ID)
			next = 6
		case 6:
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.SubscribeOptions.Info))
			next = 7
		case 7:
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			i = cfjson.Bool(b, i, &m.SubscribeOptions.Presence)
			next = 8
		case 8:
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			if cfjson.IsNull(b, i) {
				m.SubscribeOptions.ExpireAt = nil
				i += 4
			} else {
				if m.SubscribeOptions.ExpireAt == nil {
					m.SubscribeOptions.ExpireAt = new(int64)
				}
				i = cfjson.Int(b, i, m.SubscribeOptions.ExpireAt)
			}
			next = 9
		case 9:
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			if m.Extra == nil {
				m.Extra = new(Extra)
			}
			i = cfjson.String(b, i, f, &m.Extra.Note)
			next = 10
		case 10:
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			if m.Extra == nil {
				m.Extra = new(Extra)
			}
			i = cfjson.Int(b, i, &m.Extra.Shard)
			next = 11
		case 11:
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			i = cfjson.String(b, i, f, &m.Channel)
			next = 12
		case 12:
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			i = cfjson.String(b, i, f, &m.Subject)
			next = 13
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Depth) AppendJSON(b []byte) []byte {
	b = append(b, "{\"Y\":"...)
	b = cfjson.AppendString(b, m.Middle.Deep.Y)
	b = append(b, ",\"X\":"...)
	b = cfjson.AppendString(b, m.Shallow.X)
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Depth) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 4 && string(b[i:i+4]) == "\"Y\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+4)
			}
		case 1:
			if len(b)-i >= 4 && string(b[i:i+4]) == "\"X\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+4)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "Y":
				id = 0
			case "X":
				id = 1
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.Middle.Deep.Y)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.Shallow.X)
			next = 2
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Tie) AppendJSON(b []byte) []byte {
	b = append(b, "{\"W\":"...)
	b = cfjson.AppendInt(b, int64(m.Two.W))
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Tie) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		if next == 0 && len(b)-i >= 4 && string(b[i:i+4]) == "\"W\":" {
			id = 0
			i = cfjson.SkipSpace(b, i+4)
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			if string(key) == "W" {
				id = 0
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Int(b, i, &m.Two.W)
			next = 1
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *TagWins) AppendJSON(b []byte) []byte {
	b = append(b, "{\"N\":"...)
	b = cfjson.AppendString(b, m.Tagged.V)
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *TagWins) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		if next == 0 && len(b)-i >= 4 && string(b[i:i+4]) == "\"N\":" {
			id = 0
			i = cfjson.SkipSpace(b, i+4)
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			if string(key) == "N" {
				id = 0
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.Tagged.V)
			next = 1
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *DeepTie) AppendJSON(b []byte) []byte {
	b = append(b, "{\"W\":"...)
	b = cfjson.AppendInt(b, int64(m.Tie.Two.W))
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *DeepTie) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		if next == 0 && len(b)-i >= 4 && string(b[i:i+4]) == "\"W\":" {
			id = 0
			i = cfjson.SkipSpace(b, i+4)
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			if string(key) == "W" {
				id = 0
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Int(b, i, &m.Tie.Two.W)
			next = 1
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *SubscribeOptions) AppendJSON(b []byte) []byte {
	s := len(b)
	if len(m.Info) != 0 {
		b = append(b, ",\"info\":"...)
		b = cfjson.AppendRaw(b, m.Info)
	}
	if m.Presence {
		b = append(b, ",\"presence\":true"...)
	}
	if m.ExpireAt != nil {
		b = append(b, ",\"expire_at\":"...)
		b = cfjson.AppendInt(b, (*m.ExpireAt))
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *SubscribeOptions) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"info\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+7)
			}
		case 1:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"presence\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+11)
			}
		case 2:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"expire_at\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+12)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "info":
				id = 0
			case "presence":
				id = 1
			case "expire_at":
				id = 2
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Info))
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Bool(b, i, &m.Presence)
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			if cfjson.IsNull(b, i) {
				m.ExpireAt = nil
				i += 4
			} else {
				if m.ExpireAt == nil {
					m.ExpireAt = new(int64)
				}
				i = cfjson.Int(b, i, m.ExpireAt)
			}
			next = 3
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// appendJSONExtCapability appends the JSON encoding of m to b.
func appendJSONExtCapability(b []byte, m *ext.Capability) []byte {
	s := len(b)
	if len(m.Channels) != 0 {
		b = append(b, ",\"channels\":"...)
		b = append(b, '[')
		for n1, e2 := range m.Channels {
			if n1 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e2)
		}
		b = append(b, ']')
	}
	if m.Match != "" {
		b = append(b, ",\"match\":"...)
		b = cfjson.AppendString(b, string(m.Match))
	}
	if len(m.Allow) != 0 {
		b = append(b, ",\"allow\":"...)
		b = append(b, '[')
		for n3, e4 := range m.Allow {
			if n3 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e4)
		}
		b = append(b, ']')
	}
	if m.Limits != nil {
		b = append(b, ",\"limits\":"...)
		b = appendJSONExtLimits(b, m.Limits)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// decodeJSONExtCapability decodes the JSON value at b[i] into m and returns the index after
// the value, or a negative number on error, see cfjson.Error.
func decodeJSONExtCapability(m *ext.Capability, b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"channels\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+11)
			}
		case 1:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"match\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+8)
			}
		case 2:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"allow\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+8)
			}
		case 3:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"limits\":" {
				id = 3
				i = cfjson.SkipSpace(b, i+9)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "channels":
				id = 0
			case "match":
				id = 1
			case "allow":
				id = 2
			case "limits":
				id = 3
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			if cfjson.IsNull(b, i) {
				m.Channels = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Channels == nil {
						m.Channels = []string{}
					} else {
						m.Channels = m.Channels[:0]
					}
				} else {
					if cap(m.Channels) == 0 {
						m.Channels = make([]string, 0, 10)
					} else {
						m.Channels = m.Channels[:0]
					}
					for {
						var e1 string
						i = cfjson.String(b, i, f, &e1)
						if i < 0 {
							return i
						}
						m.Channels = append(m.Channels, e1)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, (*string)(&m.Match))
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			if cfjson.IsNull(b, i) {
				m.Allow = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Allow == nil {
						m.Allow = []string{}
					} else {
						m.Allow = m.Allow[:0]
					}
				} else {
					if cap(m.Allow) == 0 {
						m.Allow = make([]string, 0, 10)
					} else {
						m.Allow = m.Allow[:0]
					}
					for {
						var e2 string
						i = cfjson.String(b, i, f, &e2)
						if i < 0 {
							return i
						}
						m.Allow = append(m.Allow, e2)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 3
		case 3:
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			if cfjson.IsNull(b, i) {
				m.Limits = nil
				i += 4
			} else {
				if m.Limits == nil {
					m.Limits = new(ext.Limits)
				}
				i = decodeJSONExtLimits(m.Limits, b, i, f)
			}
			next = 4
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// appendJSONExtLimits appends the JSON encoding of m to b.
func appendJSONExtLimits(b []byte, m *ext.Limits) []byte {
	s := len(b)
	if m.Rate != 0 {
		b = append(b, ",\"rate\":"...)
		b = cfjson.AppendFloat64(b, m.Rate)
	}
	if m.Burst != 0 {
		b = append(b, ",\"burst\":"...)
		b = cfjson.AppendInt(b, int64(m.Burst))
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// decodeJSONExtLimits decodes the JSON value at b[i] into m and returns the index after
// the value, or a negative number on error, see cfjson.Error.
func decodeJSONExtLimits(m *ext.Limits, b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"rate\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+7)
			}
		case 1:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"burst\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+8)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "rate":
				id = 0
			case "burst":
				id = 1
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Float(b, i, &m.Rate)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Int(b, i, &m.Burst)
			next = 2
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}
