#!/bin/bash
#
# Regenerates ../../cfprotobuf/BENCHMARKS.md from the raw benchmark output in
# results/. Run it through `make protobuf-bench-doc` in the repository root.
#
# results/<machine>.txt           - output of the benchmarks of this module
#                                   (`make protobuf-bench` writes bench.txt,
#                                   move it there under the name of the machine);
# results/<machine>.before.txt,
# results/<machine>.after.txt     - the protocol benchmarks with type=protobuf
#                                   of bench.ref.txt and bench.head.txt written
#                                   by `make bench-compare REF=v0.22.1`.
#
# Requires benchstat: go install golang.org/x/perf/cmd/benchstat@latest

set -euo pipefail

cd "$(dirname "$0")"

if ! command -v benchstat >/dev/null 2>&1; then
  echo "error: benchstat not found in PATH" >&2
  exit 1
fi

out=../../cfprotobuf/BENCHMARKS.md

# table FILE FILTER UNIT prints one benchstat table (sec/op or allocs/op) with
# implementations as columns and messages as rows.
table() {
  echo '```'
  # A table starts with the line naming the implementations, followed by the
  # line naming the unit, and ends with an empty line.
  benchstat -filter "$2" -col /impl -row /msg "$1" 2>/dev/null |
    awk -v unit="$3" '
      done { next }
      !found && index($0, unit) { found = 1; print prev }
      found && /^ *$/ { done = 1; next }
      found { print }
      { prev = $0 }
    ' | sed -e 's/ *$//'
  echo '```'
}

{
  cat <<'HEADER'
# Benchmarks

cfprotobuf against what it replaced in `github.com/centrifugal/protocol`:
[vtprotobuf](https://github.com/planetscale/vtprotobuf).

This file is generated by `make protobuf-bench-doc` from the raw output kept
in [internal/cfprotobufcmp/results](../internal/cfprotobufcmp/results). The
benchmarks live in [internal/cfprotobufcmp](../internal/cfprotobufcmp), a
module which has both implementations as methods of the very same struct
types, so both do the same work on the same values. The tables are
`benchstat` output: 10 samples per benchmark, the first column is
vtprotobuf, `vs base` is the change relative to it.

The goal here was not speed. vtprotobuf generates good code, and cfprotobuf
generates much the same: what is measured is that replacing it costs
nothing, while decoding does more than it did. cfprotobuf checks that
strings are valid UTF-8, as the Protobuf specification requires and as
google.golang.org/protobuf does; vtprotobuf does not.

The messages are the ones the JSON benchmarks use, see
[cfjson/BENCHMARKS.md](../cfjson/BENCHMARKS.md).

How to read the sections:

- **Marshal** is encoding into a new slice, which is what the Protobuf
  encoders of `protocol` do.
- **Marshal, codec only** sizes a message and writes it into a buffer which
  is reused, leaving only the generated code to compare.
- **Unmarshal** is decoding into a new message.
- **protocol before and after** are the benchmarks of the `protocol`
  package itself (`bench_test.go` in the repository root, `type=protobuf`), run
  against v0.22.1, the last release before the switch to cfprotobuf, and against
  this branch: `make bench-compare REF=v0.22.1` in the repository root.
HEADER

  for file in results/*.txt; do
    case "$file" in
    *.before.txt | *.after.txt) continue ;;
    esac
    machine=$(basename "$file" .txt)
    echo
    echo "## $machine"
    echo
    echo '```'
    grep -E '^(goos|goarch|cpu):' "$file" | sort -u
    echo '```'

    echo
    echo "### Marshal"
    echo
    table "$file" ".name:Marshal" "sec/op"
    echo
    echo "Allocations:"
    echo
    table "$file" ".name:Marshal" "allocs/op"

    echo
    echo "### Marshal, codec only"
    echo
    table "$file" ".name:MarshalTo" "sec/op"

    echo
    echo "### Unmarshal"
    echo
    table "$file" ".name:Unmarshal" "sec/op"
    echo
    echo "Allocations:"
    echo
    table "$file" ".name:Unmarshal" "allocs/op"

    before="results/$machine.before.txt"
    after="results/$machine.after.txt"
    if [[ -f "$before" && -f "$after" ]]; then
      echo
      echo "### protocol before and after"
      echo
      echo '```'
      benchstat "before=$before" "after=$after" 2>/dev/null | sed -e 's/ *$//' | grep -v '^\(goos\|goarch\|pkg\|cpu\):'
      echo '```'
    fi
  done
} >"$out"

echo "wrote $out"
