// Code generated from types.go. DO NOT EDIT.

package cfprotobufcmp

// allTypes has a constructor for every message type.
var allTypes = []func() message{
	func() message { return new(Error) },
	func() message { return new(EmulationRequest) },
	func() message { return new(Command) },
	func() message { return new(Reply) },
	func() message { return new(Push) },
	func() message { return new(Dictionary) },
	func() message { return new(ClientInfo) },
	func() message { return new(Publication) },
	func() message { return new(Join) },
	func() message { return new(Leave) },
	func() message { return new(Unsubscribe) },
	func() message { return new(Subscribe) },
	func() message { return new(Message) },
	func() message { return new(Connect) },
	func() message { return new(Disconnect) },
	func() message { return new(Refresh) },
	func() message { return new(ConnectRequest) },
	func() message { return new(ConnectResult) },
	func() message { return new(RefreshRequest) },
	func() message { return new(RefreshResult) },
	func() message { return new(SubscribeRequest) },
	func() message { return new(SubscribeResult) },
	func() message { return new(KeyedItem) },
	func() message { return new(TrackBatch) },
	func() message { return new(SubRefreshRequest) },
	func() message { return new(SubRefreshResult) },
	func() message { return new(UnsubscribeRequest) },
	func() message { return new(UnsubscribeResult) },
	func() message { return new(PublishRequest) },
	func() message { return new(PublishResult) },
	func() message { return new(PresenceRequest) },
	func() message { return new(PresenceResult) },
	func() message { return new(PresenceStatsRequest) },
	func() message { return new(PresenceStatsResult) },
	func() message { return new(StreamPosition) },
	func() message { return new(HistoryRequest) },
	func() message { return new(HistoryResult) },
	func() message { return new(PingRequest) },
	func() message { return new(PingResult) },
	func() message { return new(RPCRequest) },
	func() message { return new(RPCResult) },
	func() message { return new(SendRequest) },
	func() message { return new(FilterNode) },
}
