// Code generated by cfjson. DO NOT EDIT.

package testtypes

import (
	cfjson "github.com/centrifugal/protocol/cfjson"
)

// AppendJSON appends the JSON encoding of m to b.
func (m *Empty) AppendJSON(b []byte) []byte {
	return append(b, '{', '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Empty) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	for {
		_, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		i = cfjson.Skip(b, i, f)
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Leaf) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.ID != 0 {
		b = append(b, ",\"id\":"...)
		b = cfjson.AppendUint(b, uint64(m.ID))
	}
	if m.Text != "" {
		b = append(b, ",\"text\":"...)
		b = cfjson.AppendString(b, m.Text)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Leaf) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 5 && string(b[i:i+5]) == "\"id\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+5)
			}
		case 1:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"text\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+7)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "id":
				id = 0
			case "text":
				id = 1
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Uint(b, i, &m.ID)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.Text)
			next = 2
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *All) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.String != "" {
		b = append(b, ",\"string\":"...)
		b = cfjson.AppendString(b, m.String)
	}
	if m.Bool {
		b = append(b, ",\"bool\":true"...)
	}
	if m.Int != 0 {
		b = append(b, ",\"int\":"...)
		b = cfjson.AppendInt(b, int64(m.Int))
	}
	if m.Int8 != 0 {
		b = append(b, ",\"int8\":"...)
		b = cfjson.AppendInt(b, int64(m.Int8))
	}
	if m.Int16 != 0 {
		b = append(b, ",\"int16\":"...)
		b = cfjson.AppendInt(b, int64(m.Int16))
	}
	if m.Int32 != 0 {
		b = append(b, ",\"int32\":"...)
		b = cfjson.AppendInt(b, int64(m.Int32))
	}
	if m.Int64 != 0 {
		b = append(b, ",\"int64\":"...)
		b = cfjson.AppendInt(b, m.Int64)
	}
	if m.Uint != 0 {
		b = append(b, ",\"uint\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint))
	}
	if m.Uint8 != 0 {
		b = append(b, ",\"uint8\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint8))
	}
	if m.Uint16 != 0 {
		b = append(b, ",\"uint16\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint16))
	}
	if m.Uint32 != 0 {
		b = append(b, ",\"uint32\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint32))
	}
	if m.Uint64 != 0 {
		b = append(b, ",\"uint64\":"...)
		b = cfjson.AppendUint(b, m.Uint64)
	}
	if m.Float32 != 0 {
		b = append(b, ",\"float32\":"...)
		b = cfjson.AppendFloat32(b, m.Float32)
	}
	if m.Float64 != 0 {
		b = append(b, ",\"float64\":"...)
		b = cfjson.AppendFloat64(b, m.Float64)
	}
	if len(m.Raw) != 0 {
		b = append(b, ",\"raw\":"...)
		b = cfjson.AppendRaw(b, m.Raw)
	}
	if m.Level != 0 {
		b = append(b, ",\"level\":"...)
		b = cfjson.AppendInt(b, int64(m.Level))
	}
	if m.Name != "" {
		b = append(b, ",\"name\":"...)
		b = cfjson.AppendString(b, string(m.Name))
	}
	if len(m.Labels) != 0 {
		b = append(b, ",\"labels\":"...)
		s1 := len(b)
		for k2, e3 := range m.Labels {
			b = append(b, ',')
			b = cfjson.AppendString(b, k2)
			b = append(b, ':')
			b = cfjson.AppendString(b, e3)
		}
		b[s1] = '{'
		b = append(b, '}')
	}
	if len(m.Names) != 0 {
		b = append(b, ",\"names\":"...)
		b = append(b, '[')
		for n4, e5 := range m.Names {
			if n4 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, string(e5))
		}
		b = append(b, ']')
	}
	b = append(b, ",\"leaf\":"...)
	b = m.Leaf.AppendJSON(b)
	if m.LeafPtr != nil {
		b = append(b, ",\"leaf_ptr\":"...)
		b = m.LeafPtr.AppendJSON(b)
	}
	if m.Self != nil {
		b = append(b, ",\"self\":"...)
		b = m.Self.AppendJSON(b)
	}
	if m.StrPtr != nil {
		b = append(b, ",\"str_ptr\":"...)
		b = cfjson.AppendString(b, (*m.StrPtr))
	}
	if m.IntPtr != nil {
		b = append(b, ",\"int_ptr\":"...)
		b = cfjson.AppendInt(b, (*m.IntPtr))
	}
	if len(m.Strings) != 0 {
		b = append(b, ",\"strings\":"...)
		b = append(b, '[')
		for n6, e7 := range m.Strings {
			if n6 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e7)
		}
		b = append(b, ']')
	}
	if len(m.Ints) != 0 {
		b = append(b, ",\"ints\":"...)
		b = append(b, '[')
		for n8, e9 := range m.Ints {
			if n8 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendInt(b, e9)
		}
		b = append(b, ']')
	}
	if len(m.Floats) != 0 {
		b = append(b, ",\"floats\":"...)
		b = append(b, '[')
		for n10, e11 := range m.Floats {
			if n10 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendFloat64(b, e11)
		}
		b = append(b, ']')
	}
	if len(m.Bools) != 0 {
		b = append(b, ",\"bools\":"...)
		b = append(b, '[')
		for n12, e13 := range m.Bools {
			if n12 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendBool(b, e13)
		}
		b = append(b, ']')
	}
	if len(m.Raws) != 0 {
		b = append(b, ",\"raws\":"...)
		b = append(b, '[')
		for n14, e15 := range m.Raws {
			if n14 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendRaw(b, e15)
		}
		b = append(b, ']')
	}
	if len(m.Leaves) != 0 {
		b = append(b, ",\"leaves\":"...)
		b = append(b, '[')
		for n16, e17 := range m.Leaves {
			if n16 != 0 {
				b = append(b, ',')
			}
			b = e17.AppendJSON(b)
		}
		b = append(b, ']')
	}
	if len(m.LeafPtrs) != 0 {
		b = append(b, ",\"leaf_ptrs\":"...)
		b = append(b, '[')
		for n18, e19 := range m.LeafPtrs {
			if n18 != 0 {
				b = append(b, ',')
			}
			if e19 == nil {
				b = append(b, "null"...)
			} else {
				b = e19.AppendJSON(b)
			}
		}
		b = append(b, ']')
	}
	if len(m.Matrix) != 0 {
		b = append(b, ",\"matrix\":"...)
		b = append(b, '[')
		for n20, e21 := range m.Matrix {
			if n20 != 0 {
				b = append(b, ',')
			}
			if e21 == nil {
				b = append(b, "null"...)
			} else {
				b = append(b, '[')
				for n22, e23 := range e21 {
					if n22 != 0 {
						b = append(b, ',')
					}
					b = cfjson.AppendUint(b, uint64(e23))
				}
				b = append(b, ']')
			}
		}
		b = append(b, ']')
	}
	if len(m.StrMap) != 0 {
		b = append(b, ",\"str_map\":"...)
		s24 := len(b)
		for k25, e26 := range m.StrMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k25)
			b = append(b, ':')
			b = cfjson.AppendString(b, e26)
		}
		b[s24] = '{'
		b = append(b, '}')
	}
	if len(m.FloatMap) != 0 {
		b = append(b, ",\"float_map\":"...)
		s27 := len(b)
		for k28, e29 := range m.FloatMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k28)
			b = append(b, ':')
			b = cfjson.AppendFloat64(b, e29)
		}
		b[s27] = '{'
		b = append(b, '}')
	}
	if len(m.LeafMap) != 0 {
		b = append(b, ",\"leaf_map\":"...)
		s30 := len(b)
		for k31, e32 := range m.LeafMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k31)
			b = append(b, ':')
			if e32 == nil {
				b = append(b, "null"...)
			} else {
				b = e32.AppendJSON(b)
			}
		}
		b[s30] = '{'
		b = append(b, '}')
	}
	if len(m.ListMap) != 0 {
		b = append(b, ",\"list_map\":"...)
		s33 := len(b)
		for k34, e35 := range m.ListMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k34)
			b = append(b, ':')
			if e35 == nil {
				b = append(b, "null"...)
			} else {
				b = append(b, '[')
				for n36, e37 := range e35 {
					if n36 != 0 {
						b = append(b, ',')
					}
					b = cfjson.AppendString(b, e37)
				}
				b = append(b, ']')
			}
		}
		b[s33] = '{'
		b = append(b, '}')
	}
	if len(m.NameMap) != 0 {
		b = append(b, ",\"name_map\":"...)
		s38 := len(b)
		for k39, e40 := range m.NameMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, string(k39))
			b = append(b, ':')
			b = cfjson.AppendInt(b, int64(e40))
		}
		b[s38] = '{'
		b = append(b, '}')
	}
	if m.MixedCase != "" {
		b = append(b, ",\"mixedCase\":"...)
		b = cfjson.AppendString(b, m.MixedCase)
	}
	b = append(b, ",\"Untagged\":"...)
	b = cfjson.AppendString(b, m.Untagged)
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *All) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	if f += cfjson.DepthStep; f >= cfjson.DepthLimit {
		return ^i
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"string\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+9)
			}
		case 1:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"bool\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+7)
			}
		case 2:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"int\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+6)
			}
		case 3:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"int8\":" {
				id = 3
				i = cfjson.SkipSpace(b, i+7)
			}
		case 4:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"int16\":" {
				id = 4
				i = cfjson.SkipSpace(b, i+8)
			}
		case 5:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"int32\":" {
				id = 5
				i = cfjson.SkipSpace(b, i+8)
			}
		case 6:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"int64\":" {
				id = 6
				i = cfjson.SkipSpace(b, i+8)
			}
		case 7:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"uint\":" {
				id = 7
				i = cfjson.SkipSpace(b, i+7)
			}
		case 8:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"uint8\":" {
				id = 8
				i = cfjson.SkipSpace(b, i+8)
			}
		case 9:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"uint16\":" {
				id = 9
				i = cfjson.SkipSpace(b, i+9)
			}
		case 10:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"uint32\":" {
				id = 10
				i = cfjson.SkipSpace(b, i+9)
			}
		case 11:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"uint64\":" {
				id = 11
				i = cfjson.SkipSpace(b, i+9)
			}
		case 12:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"float32\":" {
				id = 12
				i = cfjson.SkipSpace(b, i+10)
			}
		case 13:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"float64\":" {
				id = 13
				i = cfjson.SkipSpace(b, i+10)
			}
		case 14:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"raw\":" {
				id = 14
				i = cfjson.SkipSpace(b, i+6)
			}
		case 15:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"level\":" {
				id = 15
				i = cfjson.SkipSpace(b, i+8)
			}
		case 16:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"name\":" {
				id = 16
				i = cfjson.SkipSpace(b, i+7)
			}
		case 17:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"labels\":" {
				id = 17
				i = cfjson.SkipSpace(b, i+9)
			}
		case 18:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"names\":" {
				id = 18
				i = cfjson.SkipSpace(b, i+8)
			}
		case 19:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"leaf\":" {
				id = 19
				i = cfjson.SkipSpace(b, i+7)
			}
		case 20:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"leaf_ptr\":" {
				id = 20
				i = cfjson.SkipSpace(b, i+11)
			}
		case 21:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"self\":" {
				id = 21
				i = cfjson.SkipSpace(b, i+7)
			}
		case 22:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"str_ptr\":" {
				id = 22
				i = cfjson.SkipSpace(b, i+10)
			}
		case 23:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"int_ptr\":" {
				id = 23
				i = cfjson.SkipSpace(b, i+10)
			}
		case 24:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"strings\":" {
				id = 24
				i = cfjson.SkipSpace(b, i+10)
			}
		case 25:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"ints\":" {
				id = 25
				i = cfjson.SkipSpace(b, i+7)
			}
		case 26:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"floats\":" {
				id = 26
				i = cfjson.SkipSpace(b, i+9)
			}
		case 27:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"bools\":" {
				id = 27
				i = cfjson.SkipSpace(b, i+8)
			}
		case 28:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"raws\":" {
				id = 28
				i = cfjson.SkipSpace(b, i+7)
			}
		case 29:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"leaves\":" {
				id = 29
				i = cfjson.SkipSpace(b, i+9)
			}
		case 30:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"leaf_ptrs\":" {
				id = 30
				i = cfjson.SkipSpace(b, i+12)
			}
		case 31:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"matrix\":" {
				id = 31
				i = cfjson.SkipSpace(b, i+9)
			}
		case 32:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"str_map\":" {
				id = 32
				i = cfjson.SkipSpace(b, i+10)
			}
		case 33:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"float_map\":" {
				id = 33
				i = cfjson.SkipSpace(b, i+12)
			}
		case 34:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"leaf_map\":" {
				id = 34
				i = cfjson.SkipSpace(b, i+11)
			}
		case 35:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"list_map\":" {
				id = 35
				i = cfjson.SkipSpace(b, i+11)
			}
		case 36:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"name_map\":" {
				id = 36
				i = cfjson.SkipSpace(b, i+11)
			}
		case 37:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"mixedCase\":" {
				id = 37
				i = cfjson.SkipSpace(b, i+12)
			}
		case 38:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"Untagged\":" {
				id = 38
				i = cfjson.SkipSpace(b, i+11)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "string":
				id = 0
			case "bool":
				id = 1
			case "int":
				id = 2
			case "int8":
				id = 3
			case "int16":
				id = 4
			case "int32":
				id = 5
			case "int64":
				id = 6
			case "uint":
				id = 7
			case "uint8":
				id = 8
			case "uint16":
				id = 9
			case "uint32":
				id = 10
			case "uint64":
				id = 11
			case "float32":
				id = 12
			case "float64":
				id = 13
			case "raw":
				id = 14
			case "level":
				id = 15
			case "name":
				id = 16
			case "labels":
				id = 17
			case "names":
				id = 18
			case "leaf":
				id = 19
			case "leaf_ptr":
				id = 20
			case "self":
				id = 21
			case "str_ptr":
				id = 22
			case "int_ptr":
				id = 23
			case "strings":
				id = 24
			case "ints":
				id = 25
			case "floats":
				id = 26
			case "bools":
				id = 27
			case "raws":
				id = 28
			case "leaves":
				id = 29
			case "leaf_ptrs":
				id = 30
			case "matrix":
				id = 31
			case "str_map":
				id = 32
			case "float_map":
				id = 33
			case "leaf_map":
				id = 34
			case "list_map":
				id = 35
			case "name_map":
				id = 36
			case "mixedCase":
				id = 37
			case "Untagged":
				id = 38
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.String)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Bool(b, i, &m.Bool)
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.Int(b, i, &m.Int)
			next = 3
		case 3:
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			i = cfjson.Int(b, i, &m.Int8)
			next = 4
		case 4:
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			i = cfjson.Int(b, i, &m.Int16)
			next = 5
		case 5:
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			i = cfjson.Int(b, i, &m.Int32)
			next = 6
		case 6:
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = cfjson.Int(b, i, &m.Int64)
			next = 7
		case 7:
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			i = cfjson.Uint(b, i, &m.Uint)
			next = 8
		case 8:
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			i = cfjson.Uint(b, i, &m.Uint8)
			next = 9
		case 9:
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			i = cfjson.Uint(b, i, &m.Uint16)
			next = 10
		case 10:
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			i = cfjson.Uint(b, i, &m.Uint32)
			next = 11
		case 11:
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			i = cfjson.Uint(b, i, &m.Uint64)
			next = 12
		case 12:
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			i = cfjson.Float(b, i, &m.Float32)
			next = 13
		case 13:
			if seen0&0x2000 != 0 {
				return ^i
			}
			seen0 |= 0x2000
			i = cfjson.Float(b, i, &m.Float64)
			next = 14
		case 14:
			if seen0&0x4000 != 0 {
				return ^i
			}
			seen0 |= 0x4000
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Raw))
			next = 15
		case 15:
			if seen0&0x8000 != 0 {
				return ^i
			}
			seen0 |= 0x8000
			i = cfjson.Int(b, i, &m.Level)
			next = 16
		case 16:
			if seen0&0x10000 != 0 {
				return ^i
			}
			seen0 |= 0x10000
			i = cfjson.String(b, i, f, (*string)(&m.Name))
			next = 17
		case 17:
			if seen0&0x20000 != 0 {
				return ^i
			}
			seen0 |= 0x20000
			if cfjson.IsNull(b, i) {
				m.Labels = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.Labels = make(Labels)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n3 := 0
					for {
						var k1 string
						i = cfjson.MapKey(b, i, f, &k1)
						if i < 0 {
							return i
						}
						var e2 string
						i = cfjson.String(b, i, f, &e2)
						if i < 0 {
							return i
						}
						m.Labels[k1] = e2
						n3++
						if len(m.Labels) != n3 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 18
		case 18:
			if seen0&0x40000 != 0 {
				return ^i
			}
			seen0 |= 0x40000
			if cfjson.IsNull(b, i) {
				m.Names = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Names == nil {
						m.Names = Names{}
					} else {
						m.Names = m.Names[:0]
					}
				} else {
					if cap(m.Names) == 0 {
						m.Names = make(Names, 0, 10)
					} else {
						m.Names = m.Names[:0]
					}
					for {
						var e4 Name
						i = cfjson.String(b, i, f, (*string)(&e4))
						if i < 0 {
							return i
						}
						m.Names = append(m.Names, e4)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 19
		case 19:
			if seen0&0x80000 != 0 {
				return ^i
			}
			seen0 |= 0x80000
			i = m.Leaf.DecodeJSON(b, i, f)
			next = 20
		case 20:
			if seen0&0x100000 != 0 {
				return ^i
			}
			seen0 |= 0x100000
			if cfjson.IsNull(b, i) {
				m.LeafPtr = nil
				i += 4
			} else {
				if m.LeafPtr == nil {
					m.LeafPtr = new(Leaf)
				}
				i = m.LeafPtr.DecodeJSON(b, i, f)
			}
			next = 21
		case 21:
			if seen0&0x200000 != 0 {
				return ^i
			}
			seen0 |= 0x200000
			if cfjson.IsNull(b, i) {
				m.Self = nil
				i += 4
			} else {
				if m.Self == nil {
					m.Self = new(All)
				}
				i = m.Self.DecodeJSON(b, i, f)
			}
			next = 22
		case 22:
			if seen0&0x400000 != 0 {
				return ^i
			}
			seen0 |= 0x400000
			if cfjson.IsNull(b, i) {
				m.StrPtr = nil
				i += 4
			} else {
				if m.StrPtr == nil {
					m.StrPtr = new(string)
				}
				i = cfjson.String(b, i, f, m.StrPtr)
			}
			next = 23
		case 23:
			if seen0&0x800000 != 0 {
				return ^i
			}
			seen0 |= 0x800000
			if cfjson.IsNull(b, i) {
				m.IntPtr = nil
				i += 4
			} else {
				if m.IntPtr == nil {
					m.IntPtr = new(int64)
				}
				i = cfjson.Int(b, i, m.IntPtr)
			}
			next = 24
		case 24:
			if seen0&0x1000000 != 0 {
				return ^i
			}
			seen0 |= 0x1000000
			if cfjson.IsNull(b, i) {
				m.Strings = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Strings == nil {
						m.Strings = []string{}
					} else {
						m.Strings = m.Strings[:0]
					}
				} else {
					if cap(m.Strings) == 0 {
						m.Strings = make([]string, 0, 10)
					} else {
						m.Strings = m.Strings[:0]
					}
					for {
						var e5 string
						i = cfjson.String(b, i, f, &e5)
						if i < 0 {
							return i
						}
						m.Strings = append(m.Strings, e5)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 25
		case 25:
			if seen0&0x2000000 != 0 {
				return ^i
			}
			seen0 |= 0x2000000
			if cfjson.IsNull(b, i) {
				m.Ints = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Ints == nil {
						m.Ints = []int64{}
					} else {
						m.Ints = m.Ints[:0]
					}
				} else {
					if cap(m.Ints) == 0 {
						m.Ints = make([]int64, 0, 10)
					} else {
						m.Ints = m.Ints[:0]
					}
					for {
						var e6 int64
						i = cfjson.Int(b, i, &e6)
						if i < 0 {
							return i
						}
						m.Ints = append(m.Ints, e6)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 26
		case 26:
			if seen0&0x4000000 != 0 {
				return ^i
			}
			seen0 |= 0x4000000
			if cfjson.IsNull(b, i) {
				m.Floats = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Floats == nil {
						m.Floats = []float64{}
					} else {
						m.Floats = m.Floats[:0]
					}
				} else {
					if cap(m.Floats) == 0 {
						m.Floats = make([]float64, 0, 10)
					} else {
						m.Floats = m.Floats[:0]
					}
					for {
						var e7 float64
						i = cfjson.Float(b, i, &e7)
						if i < 0 {
							return i
						}
						m.Floats = append(m.Floats, e7)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 27
		case 27:
			if seen0&0x8000000 != 0 {
				return ^i
			}
			seen0 |= 0x8000000
			if cfjson.IsNull(b, i) {
				m.Bools = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Bools == nil {
						m.Bools = []bool{}
					} else {
						m.Bools = m.Bools[:0]
					}
				} else {
					if cap(m.Bools) == 0 {
						m.Bools = make([]bool, 0, 10)
					} else {
						m.Bools = m.Bools[:0]
					}
					for {
						var e8 bool
						i = cfjson.Bool(b, i, &e8)
						if i < 0 {
							return i
						}
						m.Bools = append(m.Bools, e8)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 28
		case 28:
			if seen0&0x10000000 != 0 {
				return ^i
			}
			seen0 |= 0x10000000
			if cfjson.IsNull(b, i) {
				m.Raws = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Raws == nil {
						m.Raws = []Raw{}
					} else {
						m.Raws = m.Raws[:0]
					}
				} else {
					if cap(m.Raws) == 0 {
						m.Raws = make([]Raw, 0, 10)
					} else {
						m.Raws = m.Raws[:0]
					}
					for {
						var e9 Raw
						i = cfjson.Raw(b, i, f, (*[]byte)(&e9))
						if i < 0 {
							return i
						}
						m.Raws = append(m.Raws, e9)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 29
		case 29:
			if seen0&0x20000000 != 0 {
				return ^i
			}
			seen0 |= 0x20000000
			if cfjson.IsNull(b, i) {
				m.Leaves = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Leaves == nil {
						m.Leaves = []Leaf{}
					} else {
						m.Leaves = m.Leaves[:0]
					}
				} else {
					if cap(m.Leaves) == 0 {
						m.Leaves = make([]Leaf, 0, 10)
					} else {
						m.Leaves = m.Leaves[:0]
					}
					for {
						var e10 Leaf
						i = e10.DecodeJSON(b, i, f)
						if i < 0 {
							return i
						}
						m.Leaves = append(m.Leaves, e10)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 30
		case 30:
			if seen0&0x40000000 != 0 {
				return ^i
			}
			seen0 |= 0x40000000
			if cfjson.IsNull(b, i) {
				m.LeafPtrs = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.LeafPtrs == nil {
						m.LeafPtrs = []*Leaf{}
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
				} else {
					if cap(m.LeafPtrs) == 0 {
						m.LeafPtrs = make([]*Leaf, 0, 10)
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
					for {
						var e11 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e11 = new(Leaf)
							i = e11.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafPtrs = append(m.LeafPtrs, e11)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 31
		case 31:
			if seen0&0x80000000 != 0 {
				return ^i
			}
			seen0 |= 0x80000000
			if cfjson.IsNull(b, i) {
				m.Matrix = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Matrix == nil {
						m.Matrix = [][]uint32{}
					} else {
						m.Matrix = m.Matrix[:0]
					}
				} else {
					if cap(m.Matrix) == 0 {
						m.Matrix = make([][]uint32, 0, 10)
					} else {
						m.Matrix = m.Matrix[:0]
					}
					for {
						var e12 []uint32
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							if i >= len(b) || b[i] != '[' {
								return ^i
							}
							i = cfjson.SkipSpace(b, i+1)
							if i < len(b) && b[i] == ']' {
								i++
								e12 = []uint32{}
							} else {
								e12 = make([]uint32, 0, 10)
								for {
									var e13 uint32
									i = cfjson.Uint(b, i, &e13)
									if i < 0 {
										return i
									}
									e12 = append(e12, e13)
									i = cfjson.SkipSpace(b, i)
									if i >= len(b) {
										return ^i
									}
									if b[i] == ',' {
										i = cfjson.SkipSpace(b, i+1)
										continue
									}
									if b[i] != ']' {
										return ^i
									}
									i++
									break
								}
							}
						}
						if i < 0 {
							return i
						}
						m.Matrix = append(m.Matrix, e12)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 32
		case 32:
			if seen0&0x100000000 != 0 {
				return ^i
			}
			seen0 |= 0x100000000
			if cfjson.IsNull(b, i) {
				m.StrMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.StrMap = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n16 := 0
					for {
						var k14 string
						i = cfjson.MapKey(b, i, f, &k14)
						if i < 0 {
							return i
						}
						var e15 string
						i = cfjson.String(b, i, f, &e15)
						if i < 0 {
							return i
						}
						m.StrMap[k14] = e15
						n16++
						if len(m.StrMap) != n16 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 33
		case 33:
			if seen0&0x200000000 != 0 {
				return ^i
			}
			seen0 |= 0x200000000
			if cfjson.IsNull(b, i) {
				m.FloatMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.FloatMap = make(map[string]float64)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n19 := 0
					for {
						var k17 string
						i = cfjson.MapKey(b, i, f, &k17)
						if i < 0 {
							return i
						}
						var e18 float64
						i = cfjson.Float(b, i, &e18)
						if i < 0 {
							return i
						}
						m.FloatMap[k17] = e18
						n19++
						if len(m.FloatMap) != n19 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 34
		case 34:
			if seen0&0x400000000 != 0 {
				return ^i
			}
			seen0 |= 0x400000000
			if cfjson.IsNull(b, i) {
				m.LeafMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.LeafMap = make(map[string]*Leaf)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n22 := 0
					for {
						var k20 string
						i = cfjson.MapKey(b, i, f, &k20)
						if i < 0 {
							return i
						}
						var e21 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e21 = new(Leaf)
							i = e21.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafMap[k20] = e21
						n22++
						if len(m.LeafMap) != n22 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 35
		case 35:
			if seen0&0x800000000 != 0 {
				return ^i
			}
			seen0 |= 0x800000000
			if cfjson.IsNull(b, i) {
				m.ListMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.ListMap = make(map[string][]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n25 := 0
					for {
						var k23 string
						i = cfjson.MapKey(b, i, f, &k23)
						if i < 0 {
							return i
						}
						var e24 []string
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							if i >= len(b) || b[i] != '[' {
								return ^i
							}
							i = cfjson.SkipSpace(b, i+1)
							if i < len(b) && b[i] == ']' {
								i++
								e24 = []string{}
							} else {
								e24 = make([]string, 0, 10)
								for {
									var e26 string
									i = cfjson.String(b, i, f, &e26)
									if i < 0 {
										return i
									}
									e24 = append(e24, e26)
									i = cfjson.SkipSpace(b, i)
									if i >= len(b) {
										return ^i
									}
									if b[i] == ',' {
										i = cfjson.SkipSpace(b, i+1)
										continue
									}
									if b[i] != ']' {
										return ^i
									}
									i++
									break
								}
							}
						}
						if i < 0 {
							return i
						}
						m.ListMap[k23] = e24
						n25++
						if len(m.ListMap) != n25 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 36
		case 36:
			if seen0&0x1000000000 != 0 {
				return ^i
			}
			seen0 |= 0x1000000000
			if cfjson.IsNull(b, i) {
				m.NameMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.NameMap = make(map[Name]Level)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n29 := 0
					for {
						var k27 string
						i = cfjson.MapKey(b, i, f, &k27)
						if i < 0 {
							return i
						}
						var e28 Level
						i = cfjson.Int(b, i, &e28)
						if i < 0 {
							return i
						}
						m.NameMap[Name(k27)] = e28
						n29++
						if len(m.NameMap) != n29 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 37
		case 37:
			if seen0&0x2000000000 != 0 {
				return ^i
			}
			seen0 |= 0x2000000000
			i = cfjson.String(b, i, f, &m.MixedCase)
			next = 38
		case 38:
			if seen0&0x4000000000 != 0 {
				return ^i
			}
			seen0 |= 0x4000000000
			i = cfjson.String(b, i, f, &m.Untagged)
			next = 39
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Required) AppendJSON(b []byte) []byte {
	b = append(b, "{\"string\":"...)
	b = cfjson.AppendString(b, m.String)
	b = append(b, ",\"bool\":"...)
	b = cfjson.AppendBool(b, m.Bool)
	b = append(b, ",\"int64\":"...)
	b = cfjson.AppendInt(b, m.Int64)
	b = append(b, ",\"uint32\":"...)
	b = cfjson.AppendUint(b, uint64(m.Uint32))
	b = append(b, ",\"float64\":"...)
	b = cfjson.AppendFloat64(b, m.Float64)
	b = append(b, ",\"raw\":"...)
	b = cfjson.AppendRaw(b, m.Raw)
	b = append(b, ",\"leaf\":"...)
	b = m.Leaf.AppendJSON(b)
	b = append(b, ",\"leaf_ptr\":"...)
	if m.LeafPtr == nil {
		b = append(b, "null"...)
	} else {
		b = m.LeafPtr.AppendJSON(b)
	}
	b = append(b, ",\"str_ptr\":"...)
	if m.StrPtr == nil {
		b = append(b, "null"...)
	} else {
		b = cfjson.AppendString(b, (*m.StrPtr))
	}
	b = append(b, ",\"strings\":"...)
	if m.Strings == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for n1, e2 := range m.Strings {
			if n1 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e2)
		}
		b = append(b, ']')
	}
	b = append(b, ",\"leaf_ptrs\":"...)
	if m.LeafPtrs == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for n3, e4 := range m.LeafPtrs {
			if n3 != 0 {
				b = append(b, ',')
			}
			if e4 == nil {
				b = append(b, "null"...)
			} else {
				b = e4.AppendJSON(b)
			}
		}
		b = append(b, ']')
	}
	b = append(b, ",\"str_map\":"...)
	if m.StrMap == nil {
		b = append(b, "null"...)
	} else {
		s5 := len(b)
		for k6, e7 := range m.StrMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k6)
			b = append(b, ':')
			b = cfjson.AppendString(b, e7)
		}
		if len(b) == s5 {
			b = append(b, '{')
		} else {
			b[s5] = '{'
		}
		b = append(b, '}')
	}
	b = append(b, ",\"leaf_map\":"...)
	if m.LeafMap == nil {
		b = append(b, "null"...)
	} else {
		s8 := len(b)
		for k9, e10 := range m.LeafMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k9)
			b = append(b, ':')
			if e10 == nil {
				b = append(b, "null"...)
			} else {
				b = e10.AppendJSON(b)
			}
		}
		if len(b) == s8 {
			b = append(b, '{')
		} else {
			b[s8] = '{'
		}
		b = append(b, '}')
	}
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Required) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"string\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+9)
			}
		case 1:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"bool\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+7)
			}
		case 2:
			if len(b)-i >= 8 && string(b[i:i+8]) == "\"int64\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+8)
			}
		case 3:
			if len(b)-i >= 9 && string(b[i:i+9]) == "\"uint32\":" {
				id = 3
				i = cfjson.SkipSpace(b, i+9)
			}
		case 4:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"float64\":" {
				id = 4
				i = cfjson.SkipSpace(b, i+10)
			}
		case 5:
			if len(b)-i >= 6 && string(b[i:i+6]) == "\"raw\":" {
				id = 5
				i = cfjson.SkipSpace(b, i+6)
			}
		case 6:
			if len(b)-i >= 7 && string(b[i:i+7]) == "\"leaf\":" {
				id = 6
				i = cfjson.SkipSpace(b, i+7)
			}
		case 7:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"leaf_ptr\":" {
				id = 7
				i = cfjson.SkipSpace(b, i+11)
			}
		case 8:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"str_ptr\":" {
				id = 8
				i = cfjson.SkipSpace(b, i+10)
			}
		case 9:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"strings\":" {
				id = 9
				i = cfjson.SkipSpace(b, i+10)
			}
		case 10:
			if len(b)-i >= 12 && string(b[i:i+12]) == "\"leaf_ptrs\":" {
				id = 10
				i = cfjson.SkipSpace(b, i+12)
			}
		case 11:
			if len(b)-i >= 10 && string(b[i:i+10]) == "\"str_map\":" {
				id = 11
				i = cfjson.SkipSpace(b, i+10)
			}
		case 12:
			if len(b)-i >= 11 && string(b[i:i+11]) == "\"leaf_map\":" {
				id = 12
				i = cfjson.SkipSpace(b, i+11)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "string":
				id = 0
			case "bool":
				id = 1
			case "int64":
				id = 2
			case "uint32":
				id = 3
			case "float64":
				id = 4
			case "raw":
				id = 5
			case "leaf":
				id = 6
			case "leaf_ptr":
				id = 7
			case "str_ptr":
				id = 8
			case "strings":
				id = 9
			case "leaf_ptrs":
				id = 10
			case "str_map":
				id = 11
			case "leaf_map":
				id = 12
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.String)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Bool(b, i, &m.Bool)
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.Int(b, i, &m.Int64)
			next = 3
		case 3:
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			i = cfjson.Uint(b, i, &m.Uint32)
			next = 4
		case 4:
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			i = cfjson.Float(b, i, &m.Float64)
			next = 5
		case 5:
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Raw))
			next = 6
		case 6:
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = m.Leaf.DecodeJSON(b, i, f)
			next = 7
		case 7:
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			if cfjson.IsNull(b, i) {
				m.LeafPtr = nil
				i += 4
			} else {
				if m.LeafPtr == nil {
					m.LeafPtr = new(Leaf)
				}
				i = m.LeafPtr.DecodeJSON(b, i, f)
			}
			next = 8
		case 8:
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			if cfjson.IsNull(b, i) {
				m.StrPtr = nil
				i += 4
			} else {
				if m.StrPtr == nil {
					m.StrPtr = new(string)
				}
				i = cfjson.String(b, i, f, m.StrPtr)
			}
			next = 9
		case 9:
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			if cfjson.IsNull(b, i) {
				m.Strings = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Strings == nil {
						m.Strings = []string{}
					} else {
						m.Strings = m.Strings[:0]
					}
				} else {
					if cap(m.Strings) == 0 {
						m.Strings = make([]string, 0, 10)
					} else {
						m.Strings = m.Strings[:0]
					}
					for {
						var e1 string
						i = cfjson.String(b, i, f, &e1)
						if i < 0 {
							return i
						}
						m.Strings = append(m.Strings, e1)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 10
		case 10:
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			if cfjson.IsNull(b, i) {
				m.LeafPtrs = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.LeafPtrs == nil {
						m.LeafPtrs = []*Leaf{}
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
				} else {
					if cap(m.LeafPtrs) == 0 {
						m.LeafPtrs = make([]*Leaf, 0, 10)
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
					for {
						var e2 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e2 = new(Leaf)
							i = e2.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafPtrs = append(m.LeafPtrs, e2)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 11
		case 11:
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			if cfjson.IsNull(b, i) {
				m.StrMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.StrMap = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n5 := 0
					for {
						var k3 string
						i = cfjson.MapKey(b, i, f, &k3)
						if i < 0 {
							return i
						}
						var e4 string
						i = cfjson.String(b, i, f, &e4)
						if i < 0 {
							return i
						}
						m.StrMap[k3] = e4
						n5++
						if len(m.StrMap) != n5 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 12
		case 12:
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			if cfjson.IsNull(b, i) {
				m.LeafMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.LeafMap = make(map[string]*Leaf)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					n8 := 0
					for {
						var k6 string
						i = cfjson.MapKey(b, i, f, &k6)
						if i < 0 {
							return i
						}
						var e7 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e7 = new(Leaf)
							i = e7.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafMap[k6] = e7
						n8++
						if len(m.LeafMap) != n8 {
							return ^i
						}
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
			next = 13
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Mixed) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.A != "" {
		b = append(b, ",\"a\":"...)
		b = cfjson.AppendString(b, m.A)
	}
	b = append(b, ",\"b\":"...)
	b = cfjson.AppendString(b, m.B)
	if m.C != "" {
		b = append(b, ",\"c\":"...)
		b = cfjson.AppendString(b, m.C)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Mixed) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	next := 0
	for {
		id := -1
		switch next {
		case 0:
			if len(b)-i >= 4 && string(b[i:i+4]) == "\"a\":" {
				id = 0
				i = cfjson.SkipSpace(b, i+4)
			}
		case 1:
			if len(b)-i >= 4 && string(b[i:i+4]) == "\"b\":" {
				id = 1
				i = cfjson.SkipSpace(b, i+4)
			}
		case 2:
			if len(b)-i >= 4 && string(b[i:i+4]) == "\"c\":" {
				id = 2
				i = cfjson.SkipSpace(b, i+4)
			}
		}
		if id < 0 {
			var key []byte
			key, i = cfjson.Key(b, i, f)
			if i < 0 {
				return i
			}
			switch string(key) {
			case "a":
				id = 0
			case "b":
				id = 1
			case "c":
				id = 2
			}
		}
		switch id {
		case 0:
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.A)
			next = 1
		case 1:
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.B)
			next = 2
		case 2:
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.String(b, i, f, &m.C)
			next = 3
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}
