// Code generated by cfjson. DO NOT EDIT.

package testtypes

import (
	cfjson "github.com/centrifugal/protocol/cfjson"
)

// AppendJSON appends the JSON encoding of m to b.
func (m *Empty) AppendJSON(b []byte) []byte {
	return append(b, '{', '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Empty) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		_ = key
		i = cfjson.Skip(b, i, f)
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Leaf) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.ID != 0 {
		b = append(b, ",\"id\":"...)
		b = cfjson.AppendUint(b, uint64(m.ID))
	}
	if m.Text != "" {
		b = append(b, ",\"text\":"...)
		b = cfjson.AppendString(b, m.Text)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Leaf) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		switch string(key) {
		case "id":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Uint(b, i, &m.ID)
		case "text":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.Text)
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *All) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.String != "" {
		b = append(b, ",\"string\":"...)
		b = cfjson.AppendString(b, m.String)
	}
	if m.Bool {
		b = append(b, ",\"bool\":"...)
		b = cfjson.AppendBool(b, m.Bool)
	}
	if m.Int != 0 {
		b = append(b, ",\"int\":"...)
		b = cfjson.AppendInt(b, int64(m.Int))
	}
	if m.Int8 != 0 {
		b = append(b, ",\"int8\":"...)
		b = cfjson.AppendInt(b, int64(m.Int8))
	}
	if m.Int16 != 0 {
		b = append(b, ",\"int16\":"...)
		b = cfjson.AppendInt(b, int64(m.Int16))
	}
	if m.Int32 != 0 {
		b = append(b, ",\"int32\":"...)
		b = cfjson.AppendInt(b, int64(m.Int32))
	}
	if m.Int64 != 0 {
		b = append(b, ",\"int64\":"...)
		b = cfjson.AppendInt(b, m.Int64)
	}
	if m.Uint != 0 {
		b = append(b, ",\"uint\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint))
	}
	if m.Uint8 != 0 {
		b = append(b, ",\"uint8\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint8))
	}
	if m.Uint16 != 0 {
		b = append(b, ",\"uint16\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint16))
	}
	if m.Uint32 != 0 {
		b = append(b, ",\"uint32\":"...)
		b = cfjson.AppendUint(b, uint64(m.Uint32))
	}
	if m.Uint64 != 0 {
		b = append(b, ",\"uint64\":"...)
		b = cfjson.AppendUint(b, m.Uint64)
	}
	if m.Float32 != 0 {
		b = append(b, ",\"float32\":"...)
		b = cfjson.AppendFloat32(b, m.Float32)
	}
	if m.Float64 != 0 {
		b = append(b, ",\"float64\":"...)
		b = cfjson.AppendFloat64(b, m.Float64)
	}
	if len(m.Raw) != 0 {
		b = append(b, ",\"raw\":"...)
		b = cfjson.AppendRaw(b, m.Raw)
	}
	if m.Level != 0 {
		b = append(b, ",\"level\":"...)
		b = cfjson.AppendInt(b, int64(m.Level))
	}
	if m.Name != "" {
		b = append(b, ",\"name\":"...)
		b = cfjson.AppendString(b, string(m.Name))
	}
	if len(m.Labels) != 0 {
		b = append(b, ",\"labels\":"...)
		s1 := len(b)
		for k2, e3 := range m.Labels {
			b = append(b, ',')
			b = cfjson.AppendString(b, k2)
			b = append(b, ':')
			b = cfjson.AppendString(b, e3)
		}
		b[s1] = '{'
		b = append(b, '}')
	}
	if len(m.Names) != 0 {
		b = append(b, ",\"names\":"...)
		b = append(b, '[')
		for n4, e5 := range m.Names {
			if n4 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, string(e5))
		}
		b = append(b, ']')
	}
	b = append(b, ",\"leaf\":"...)
	b = m.Leaf.AppendJSON(b)
	if m.LeafPtr != nil {
		b = append(b, ",\"leaf_ptr\":"...)
		b = m.LeafPtr.AppendJSON(b)
	}
	if m.Self != nil {
		b = append(b, ",\"self\":"...)
		b = m.Self.AppendJSON(b)
	}
	if m.StrPtr != nil {
		b = append(b, ",\"str_ptr\":"...)
		b = cfjson.AppendString(b, (*m.StrPtr))
	}
	if m.IntPtr != nil {
		b = append(b, ",\"int_ptr\":"...)
		b = cfjson.AppendInt(b, (*m.IntPtr))
	}
	if len(m.Strings) != 0 {
		b = append(b, ",\"strings\":"...)
		b = append(b, '[')
		for n6, e7 := range m.Strings {
			if n6 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e7)
		}
		b = append(b, ']')
	}
	if len(m.Ints) != 0 {
		b = append(b, ",\"ints\":"...)
		b = append(b, '[')
		for n8, e9 := range m.Ints {
			if n8 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendInt(b, e9)
		}
		b = append(b, ']')
	}
	if len(m.Floats) != 0 {
		b = append(b, ",\"floats\":"...)
		b = append(b, '[')
		for n10, e11 := range m.Floats {
			if n10 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendFloat64(b, e11)
		}
		b = append(b, ']')
	}
	if len(m.Bools) != 0 {
		b = append(b, ",\"bools\":"...)
		b = append(b, '[')
		for n12, e13 := range m.Bools {
			if n12 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendBool(b, e13)
		}
		b = append(b, ']')
	}
	if len(m.Raws) != 0 {
		b = append(b, ",\"raws\":"...)
		b = append(b, '[')
		for n14, e15 := range m.Raws {
			if n14 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendRaw(b, e15)
		}
		b = append(b, ']')
	}
	if len(m.Leaves) != 0 {
		b = append(b, ",\"leaves\":"...)
		b = append(b, '[')
		for n16, e17 := range m.Leaves {
			if n16 != 0 {
				b = append(b, ',')
			}
			b = e17.AppendJSON(b)
		}
		b = append(b, ']')
	}
	if len(m.LeafPtrs) != 0 {
		b = append(b, ",\"leaf_ptrs\":"...)
		b = append(b, '[')
		for n18, e19 := range m.LeafPtrs {
			if n18 != 0 {
				b = append(b, ',')
			}
			if e19 == nil {
				b = append(b, "null"...)
			} else {
				b = e19.AppendJSON(b)
			}
		}
		b = append(b, ']')
	}
	if len(m.Matrix) != 0 {
		b = append(b, ",\"matrix\":"...)
		b = append(b, '[')
		for n20, e21 := range m.Matrix {
			if n20 != 0 {
				b = append(b, ',')
			}
			if e21 == nil {
				b = append(b, "null"...)
			} else {
				b = append(b, '[')
				for n22, e23 := range e21 {
					if n22 != 0 {
						b = append(b, ',')
					}
					b = cfjson.AppendUint(b, uint64(e23))
				}
				b = append(b, ']')
			}
		}
		b = append(b, ']')
	}
	if len(m.StrMap) != 0 {
		b = append(b, ",\"str_map\":"...)
		s24 := len(b)
		for k25, e26 := range m.StrMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k25)
			b = append(b, ':')
			b = cfjson.AppendString(b, e26)
		}
		b[s24] = '{'
		b = append(b, '}')
	}
	if len(m.FloatMap) != 0 {
		b = append(b, ",\"float_map\":"...)
		s27 := len(b)
		for k28, e29 := range m.FloatMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k28)
			b = append(b, ':')
			b = cfjson.AppendFloat64(b, e29)
		}
		b[s27] = '{'
		b = append(b, '}')
	}
	if len(m.LeafMap) != 0 {
		b = append(b, ",\"leaf_map\":"...)
		s30 := len(b)
		for k31, e32 := range m.LeafMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k31)
			b = append(b, ':')
			if e32 == nil {
				b = append(b, "null"...)
			} else {
				b = e32.AppendJSON(b)
			}
		}
		b[s30] = '{'
		b = append(b, '}')
	}
	if len(m.ListMap) != 0 {
		b = append(b, ",\"list_map\":"...)
		s33 := len(b)
		for k34, e35 := range m.ListMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k34)
			b = append(b, ':')
			if e35 == nil {
				b = append(b, "null"...)
			} else {
				b = append(b, '[')
				for n36, e37 := range e35 {
					if n36 != 0 {
						b = append(b, ',')
					}
					b = cfjson.AppendString(b, e37)
				}
				b = append(b, ']')
			}
		}
		b[s33] = '{'
		b = append(b, '}')
	}
	if len(m.NameMap) != 0 {
		b = append(b, ",\"name_map\":"...)
		s38 := len(b)
		for k39, e40 := range m.NameMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, string(k39))
			b = append(b, ':')
			b = cfjson.AppendInt(b, int64(e40))
		}
		b[s38] = '{'
		b = append(b, '}')
	}
	if m.MixedCase != "" {
		b = append(b, ",\"mixedCase\":"...)
		b = cfjson.AppendString(b, m.MixedCase)
	}
	b = append(b, ",\"Untagged\":"...)
	b = cfjson.AppendString(b, m.Untagged)
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *All) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	if f += cfjson.DepthStep; f >= cfjson.DepthLimit {
		return ^i
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		switch string(key) {
		case "string":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.String)
		case "bool":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Bool(b, i, &m.Bool)
		case "int":
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.Int(b, i, &m.Int)
		case "int8":
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			i = cfjson.Int(b, i, &m.Int8)
		case "int16":
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			i = cfjson.Int(b, i, &m.Int16)
		case "int32":
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			i = cfjson.Int(b, i, &m.Int32)
		case "int64":
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = cfjson.Int(b, i, &m.Int64)
		case "uint":
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			i = cfjson.Uint(b, i, &m.Uint)
		case "uint8":
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			i = cfjson.Uint(b, i, &m.Uint8)
		case "uint16":
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			i = cfjson.Uint(b, i, &m.Uint16)
		case "uint32":
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			i = cfjson.Uint(b, i, &m.Uint32)
		case "uint64":
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			i = cfjson.Uint(b, i, &m.Uint64)
		case "float32":
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			i = cfjson.Float(b, i, &m.Float32)
		case "float64":
			if seen0&0x2000 != 0 {
				return ^i
			}
			seen0 |= 0x2000
			i = cfjson.Float(b, i, &m.Float64)
		case "raw":
			if seen0&0x4000 != 0 {
				return ^i
			}
			seen0 |= 0x4000
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Raw))
		case "level":
			if seen0&0x8000 != 0 {
				return ^i
			}
			seen0 |= 0x8000
			i = cfjson.Int(b, i, &m.Level)
		case "name":
			if seen0&0x10000 != 0 {
				return ^i
			}
			seen0 |= 0x10000
			i = cfjson.String(b, i, f, (*string)(&m.Name))
		case "labels":
			if seen0&0x20000 != 0 {
				return ^i
			}
			seen0 |= 0x20000
			if cfjson.IsNull(b, i) {
				m.Labels = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.Labels = make(Labels)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k1 string
						i = cfjson.MapKey(b, i, f, &k1)
						if i < 0 {
							return i
						}
						var e2 string
						i = cfjson.String(b, i, f, &e2)
						if i < 0 {
							return i
						}
						if _, dup := m.Labels[k1]; dup {
							return ^i
						}
						m.Labels[k1] = e2
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "names":
			if seen0&0x40000 != 0 {
				return ^i
			}
			seen0 |= 0x40000
			if cfjson.IsNull(b, i) {
				m.Names = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Names == nil {
						m.Names = Names{}
					} else {
						m.Names = m.Names[:0]
					}
				} else {
					if cap(m.Names) == 0 {
						m.Names = make(Names, 0, 10)
					} else {
						m.Names = m.Names[:0]
					}
					for {
						var e3 Name
						i = cfjson.String(b, i, f, (*string)(&e3))
						if i < 0 {
							return i
						}
						m.Names = append(m.Names, e3)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaf":
			if seen0&0x80000 != 0 {
				return ^i
			}
			seen0 |= 0x80000
			i = m.Leaf.DecodeJSON(b, i, f)
		case "leaf_ptr":
			if seen0&0x100000 != 0 {
				return ^i
			}
			seen0 |= 0x100000
			if cfjson.IsNull(b, i) {
				m.LeafPtr = nil
				i += 4
			} else {
				if m.LeafPtr == nil {
					m.LeafPtr = new(Leaf)
				}
				i = m.LeafPtr.DecodeJSON(b, i, f)
			}
		case "self":
			if seen0&0x200000 != 0 {
				return ^i
			}
			seen0 |= 0x200000
			if cfjson.IsNull(b, i) {
				m.Self = nil
				i += 4
			} else {
				if m.Self == nil {
					m.Self = new(All)
				}
				i = m.Self.DecodeJSON(b, i, f)
			}
		case "str_ptr":
			if seen0&0x400000 != 0 {
				return ^i
			}
			seen0 |= 0x400000
			if cfjson.IsNull(b, i) {
				m.StrPtr = nil
				i += 4
			} else {
				if m.StrPtr == nil {
					m.StrPtr = new(string)
				}
				i = cfjson.String(b, i, f, m.StrPtr)
			}
		case "int_ptr":
			if seen0&0x800000 != 0 {
				return ^i
			}
			seen0 |= 0x800000
			if cfjson.IsNull(b, i) {
				m.IntPtr = nil
				i += 4
			} else {
				if m.IntPtr == nil {
					m.IntPtr = new(int64)
				}
				i = cfjson.Int(b, i, m.IntPtr)
			}
		case "strings":
			if seen0&0x1000000 != 0 {
				return ^i
			}
			seen0 |= 0x1000000
			if cfjson.IsNull(b, i) {
				m.Strings = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Strings == nil {
						m.Strings = []string{}
					} else {
						m.Strings = m.Strings[:0]
					}
				} else {
					if cap(m.Strings) == 0 {
						m.Strings = make([]string, 0, 10)
					} else {
						m.Strings = m.Strings[:0]
					}
					for {
						var e4 string
						i = cfjson.String(b, i, f, &e4)
						if i < 0 {
							return i
						}
						m.Strings = append(m.Strings, e4)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "ints":
			if seen0&0x2000000 != 0 {
				return ^i
			}
			seen0 |= 0x2000000
			if cfjson.IsNull(b, i) {
				m.Ints = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Ints == nil {
						m.Ints = []int64{}
					} else {
						m.Ints = m.Ints[:0]
					}
				} else {
					if cap(m.Ints) == 0 {
						m.Ints = make([]int64, 0, 10)
					} else {
						m.Ints = m.Ints[:0]
					}
					for {
						var e5 int64
						i = cfjson.Int(b, i, &e5)
						if i < 0 {
							return i
						}
						m.Ints = append(m.Ints, e5)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "floats":
			if seen0&0x4000000 != 0 {
				return ^i
			}
			seen0 |= 0x4000000
			if cfjson.IsNull(b, i) {
				m.Floats = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Floats == nil {
						m.Floats = []float64{}
					} else {
						m.Floats = m.Floats[:0]
					}
				} else {
					if cap(m.Floats) == 0 {
						m.Floats = make([]float64, 0, 10)
					} else {
						m.Floats = m.Floats[:0]
					}
					for {
						var e6 float64
						i = cfjson.Float(b, i, &e6)
						if i < 0 {
							return i
						}
						m.Floats = append(m.Floats, e6)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "bools":
			if seen0&0x8000000 != 0 {
				return ^i
			}
			seen0 |= 0x8000000
			if cfjson.IsNull(b, i) {
				m.Bools = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Bools == nil {
						m.Bools = []bool{}
					} else {
						m.Bools = m.Bools[:0]
					}
				} else {
					if cap(m.Bools) == 0 {
						m.Bools = make([]bool, 0, 10)
					} else {
						m.Bools = m.Bools[:0]
					}
					for {
						var e7 bool
						i = cfjson.Bool(b, i, &e7)
						if i < 0 {
							return i
						}
						m.Bools = append(m.Bools, e7)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "raws":
			if seen0&0x10000000 != 0 {
				return ^i
			}
			seen0 |= 0x10000000
			if cfjson.IsNull(b, i) {
				m.Raws = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Raws == nil {
						m.Raws = []Raw{}
					} else {
						m.Raws = m.Raws[:0]
					}
				} else {
					if cap(m.Raws) == 0 {
						m.Raws = make([]Raw, 0, 10)
					} else {
						m.Raws = m.Raws[:0]
					}
					for {
						var e8 Raw
						i = cfjson.Raw(b, i, f, (*[]byte)(&e8))
						if i < 0 {
							return i
						}
						m.Raws = append(m.Raws, e8)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaves":
			if seen0&0x20000000 != 0 {
				return ^i
			}
			seen0 |= 0x20000000
			if cfjson.IsNull(b, i) {
				m.Leaves = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Leaves == nil {
						m.Leaves = []Leaf{}
					} else {
						m.Leaves = m.Leaves[:0]
					}
				} else {
					if cap(m.Leaves) == 0 {
						m.Leaves = make([]Leaf, 0, 10)
					} else {
						m.Leaves = m.Leaves[:0]
					}
					for {
						var e9 Leaf
						i = e9.DecodeJSON(b, i, f)
						if i < 0 {
							return i
						}
						m.Leaves = append(m.Leaves, e9)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaf_ptrs":
			if seen0&0x40000000 != 0 {
				return ^i
			}
			seen0 |= 0x40000000
			if cfjson.IsNull(b, i) {
				m.LeafPtrs = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.LeafPtrs == nil {
						m.LeafPtrs = []*Leaf{}
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
				} else {
					if cap(m.LeafPtrs) == 0 {
						m.LeafPtrs = make([]*Leaf, 0, 10)
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
					for {
						var e10 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e10 = new(Leaf)
							i = e10.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafPtrs = append(m.LeafPtrs, e10)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "matrix":
			if seen0&0x80000000 != 0 {
				return ^i
			}
			seen0 |= 0x80000000
			if cfjson.IsNull(b, i) {
				m.Matrix = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Matrix == nil {
						m.Matrix = [][]uint32{}
					} else {
						m.Matrix = m.Matrix[:0]
					}
				} else {
					if cap(m.Matrix) == 0 {
						m.Matrix = make([][]uint32, 0, 10)
					} else {
						m.Matrix = m.Matrix[:0]
					}
					for {
						var e11 []uint32
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							if i >= len(b) || b[i] != '[' {
								return ^i
							}
							i = cfjson.SkipSpace(b, i+1)
							if i < len(b) && b[i] == ']' {
								i++
								e11 = []uint32{}
							} else {
								e11 = make([]uint32, 0, 10)
								for {
									var e12 uint32
									i = cfjson.Uint(b, i, &e12)
									if i < 0 {
										return i
									}
									e11 = append(e11, e12)
									i = cfjson.SkipSpace(b, i)
									if i >= len(b) {
										return ^i
									}
									if b[i] == ',' {
										i = cfjson.SkipSpace(b, i+1)
										continue
									}
									if b[i] != ']' {
										return ^i
									}
									i++
									break
								}
							}
						}
						if i < 0 {
							return i
						}
						m.Matrix = append(m.Matrix, e11)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "str_map":
			if seen0&0x100000000 != 0 {
				return ^i
			}
			seen0 |= 0x100000000
			if cfjson.IsNull(b, i) {
				m.StrMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.StrMap = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k13 string
						i = cfjson.MapKey(b, i, f, &k13)
						if i < 0 {
							return i
						}
						var e14 string
						i = cfjson.String(b, i, f, &e14)
						if i < 0 {
							return i
						}
						if _, dup := m.StrMap[k13]; dup {
							return ^i
						}
						m.StrMap[k13] = e14
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "float_map":
			if seen0&0x200000000 != 0 {
				return ^i
			}
			seen0 |= 0x200000000
			if cfjson.IsNull(b, i) {
				m.FloatMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.FloatMap = make(map[string]float64)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k15 string
						i = cfjson.MapKey(b, i, f, &k15)
						if i < 0 {
							return i
						}
						var e16 float64
						i = cfjson.Float(b, i, &e16)
						if i < 0 {
							return i
						}
						if _, dup := m.FloatMap[k15]; dup {
							return ^i
						}
						m.FloatMap[k15] = e16
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaf_map":
			if seen0&0x400000000 != 0 {
				return ^i
			}
			seen0 |= 0x400000000
			if cfjson.IsNull(b, i) {
				m.LeafMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.LeafMap = make(map[string]*Leaf)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k17 string
						i = cfjson.MapKey(b, i, f, &k17)
						if i < 0 {
							return i
						}
						var e18 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e18 = new(Leaf)
							i = e18.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						if _, dup := m.LeafMap[k17]; dup {
							return ^i
						}
						m.LeafMap[k17] = e18
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "list_map":
			if seen0&0x800000000 != 0 {
				return ^i
			}
			seen0 |= 0x800000000
			if cfjson.IsNull(b, i) {
				m.ListMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.ListMap = make(map[string][]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k19 string
						i = cfjson.MapKey(b, i, f, &k19)
						if i < 0 {
							return i
						}
						var e20 []string
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							if i >= len(b) || b[i] != '[' {
								return ^i
							}
							i = cfjson.SkipSpace(b, i+1)
							if i < len(b) && b[i] == ']' {
								i++
								e20 = []string{}
							} else {
								e20 = make([]string, 0, 10)
								for {
									var e21 string
									i = cfjson.String(b, i, f, &e21)
									if i < 0 {
										return i
									}
									e20 = append(e20, e21)
									i = cfjson.SkipSpace(b, i)
									if i >= len(b) {
										return ^i
									}
									if b[i] == ',' {
										i = cfjson.SkipSpace(b, i+1)
										continue
									}
									if b[i] != ']' {
										return ^i
									}
									i++
									break
								}
							}
						}
						if i < 0 {
							return i
						}
						if _, dup := m.ListMap[k19]; dup {
							return ^i
						}
						m.ListMap[k19] = e20
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "name_map":
			if seen0&0x1000000000 != 0 {
				return ^i
			}
			seen0 |= 0x1000000000
			if cfjson.IsNull(b, i) {
				m.NameMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.NameMap = make(map[Name]Level)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k22 string
						i = cfjson.MapKey(b, i, f, &k22)
						if i < 0 {
							return i
						}
						var e23 Level
						i = cfjson.Int(b, i, &e23)
						if i < 0 {
							return i
						}
						if _, dup := m.NameMap[Name(k22)]; dup {
							return ^i
						}
						m.NameMap[Name(k22)] = e23
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "mixedCase":
			if seen0&0x2000000000 != 0 {
				return ^i
			}
			seen0 |= 0x2000000000
			i = cfjson.String(b, i, f, &m.MixedCase)
		case "Untagged":
			if seen0&0x4000000000 != 0 {
				return ^i
			}
			seen0 |= 0x4000000000
			i = cfjson.String(b, i, f, &m.Untagged)
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Required) AppendJSON(b []byte) []byte {
	b = append(b, "{\"string\":"...)
	b = cfjson.AppendString(b, m.String)
	b = append(b, ",\"bool\":"...)
	b = cfjson.AppendBool(b, m.Bool)
	b = append(b, ",\"int64\":"...)
	b = cfjson.AppendInt(b, m.Int64)
	b = append(b, ",\"uint32\":"...)
	b = cfjson.AppendUint(b, uint64(m.Uint32))
	b = append(b, ",\"float64\":"...)
	b = cfjson.AppendFloat64(b, m.Float64)
	b = append(b, ",\"raw\":"...)
	b = cfjson.AppendRaw(b, m.Raw)
	b = append(b, ",\"leaf\":"...)
	b = m.Leaf.AppendJSON(b)
	b = append(b, ",\"leaf_ptr\":"...)
	if m.LeafPtr == nil {
		b = append(b, "null"...)
	} else {
		b = m.LeafPtr.AppendJSON(b)
	}
	b = append(b, ",\"str_ptr\":"...)
	if m.StrPtr == nil {
		b = append(b, "null"...)
	} else {
		b = cfjson.AppendString(b, (*m.StrPtr))
	}
	b = append(b, ",\"strings\":"...)
	if m.Strings == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for n1, e2 := range m.Strings {
			if n1 != 0 {
				b = append(b, ',')
			}
			b = cfjson.AppendString(b, e2)
		}
		b = append(b, ']')
	}
	b = append(b, ",\"leaf_ptrs\":"...)
	if m.LeafPtrs == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for n3, e4 := range m.LeafPtrs {
			if n3 != 0 {
				b = append(b, ',')
			}
			if e4 == nil {
				b = append(b, "null"...)
			} else {
				b = e4.AppendJSON(b)
			}
		}
		b = append(b, ']')
	}
	b = append(b, ",\"str_map\":"...)
	if m.StrMap == nil {
		b = append(b, "null"...)
	} else {
		s5 := len(b)
		for k6, e7 := range m.StrMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k6)
			b = append(b, ':')
			b = cfjson.AppendString(b, e7)
		}
		if len(b) == s5 {
			b = append(b, '{')
		} else {
			b[s5] = '{'
		}
		b = append(b, '}')
	}
	b = append(b, ",\"leaf_map\":"...)
	if m.LeafMap == nil {
		b = append(b, "null"...)
	} else {
		s8 := len(b)
		for k9, e10 := range m.LeafMap {
			b = append(b, ',')
			b = cfjson.AppendString(b, k9)
			b = append(b, ':')
			if e10 == nil {
				b = append(b, "null"...)
			} else {
				b = e10.AppendJSON(b)
			}
		}
		if len(b) == s8 {
			b = append(b, '{')
		} else {
			b[s8] = '{'
		}
		b = append(b, '}')
	}
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Required) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		switch string(key) {
		case "string":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.String)
		case "bool":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.Bool(b, i, &m.Bool)
		case "int64":
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.Int(b, i, &m.Int64)
		case "uint32":
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			i = cfjson.Uint(b, i, &m.Uint32)
		case "float64":
			if seen0&0x10 != 0 {
				return ^i
			}
			seen0 |= 0x10
			i = cfjson.Float(b, i, &m.Float64)
		case "raw":
			if seen0&0x20 != 0 {
				return ^i
			}
			seen0 |= 0x20
			i = cfjson.Raw(b, i, f, (*[]byte)(&m.Raw))
		case "leaf":
			if seen0&0x40 != 0 {
				return ^i
			}
			seen0 |= 0x40
			i = m.Leaf.DecodeJSON(b, i, f)
		case "leaf_ptr":
			if seen0&0x80 != 0 {
				return ^i
			}
			seen0 |= 0x80
			if cfjson.IsNull(b, i) {
				m.LeafPtr = nil
				i += 4
			} else {
				if m.LeafPtr == nil {
					m.LeafPtr = new(Leaf)
				}
				i = m.LeafPtr.DecodeJSON(b, i, f)
			}
		case "str_ptr":
			if seen0&0x100 != 0 {
				return ^i
			}
			seen0 |= 0x100
			if cfjson.IsNull(b, i) {
				m.StrPtr = nil
				i += 4
			} else {
				if m.StrPtr == nil {
					m.StrPtr = new(string)
				}
				i = cfjson.String(b, i, f, m.StrPtr)
			}
		case "strings":
			if seen0&0x200 != 0 {
				return ^i
			}
			seen0 |= 0x200
			if cfjson.IsNull(b, i) {
				m.Strings = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.Strings == nil {
						m.Strings = []string{}
					} else {
						m.Strings = m.Strings[:0]
					}
				} else {
					if cap(m.Strings) == 0 {
						m.Strings = make([]string, 0, 10)
					} else {
						m.Strings = m.Strings[:0]
					}
					for {
						var e1 string
						i = cfjson.String(b, i, f, &e1)
						if i < 0 {
							return i
						}
						m.Strings = append(m.Strings, e1)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaf_ptrs":
			if seen0&0x400 != 0 {
				return ^i
			}
			seen0 |= 0x400
			if cfjson.IsNull(b, i) {
				m.LeafPtrs = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '[' {
					return ^i
				}
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == ']' {
					i++
					if m.LeafPtrs == nil {
						m.LeafPtrs = []*Leaf{}
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
				} else {
					if cap(m.LeafPtrs) == 0 {
						m.LeafPtrs = make([]*Leaf, 0, 10)
					} else {
						m.LeafPtrs = m.LeafPtrs[:0]
					}
					for {
						var e2 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e2 = new(Leaf)
							i = e2.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						m.LeafPtrs = append(m.LeafPtrs, e2)
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != ']' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "str_map":
			if seen0&0x800 != 0 {
				return ^i
			}
			seen0 |= 0x800
			if cfjson.IsNull(b, i) {
				m.StrMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.StrMap = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k3 string
						i = cfjson.MapKey(b, i, f, &k3)
						if i < 0 {
							return i
						}
						var e4 string
						i = cfjson.String(b, i, f, &e4)
						if i < 0 {
							return i
						}
						if _, dup := m.StrMap[k3]; dup {
							return ^i
						}
						m.StrMap[k3] = e4
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		case "leaf_map":
			if seen0&0x1000 != 0 {
				return ^i
			}
			seen0 |= 0x1000
			if cfjson.IsNull(b, i) {
				m.LeafMap = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.LeafMap = make(map[string]*Leaf)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k5 string
						i = cfjson.MapKey(b, i, f, &k5)
						if i < 0 {
							return i
						}
						var e6 *Leaf
						if cfjson.IsNull(b, i) {
							i += 4
						} else {
							e6 = new(Leaf)
							i = e6.DecodeJSON(b, i, f)
						}
						if i < 0 {
							return i
						}
						if _, dup := m.LeafMap[k5]; dup {
							return ^i
						}
						m.LeafMap[k5] = e6
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Mixed) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.A != "" {
		b = append(b, ",\"a\":"...)
		b = cfjson.AppendString(b, m.A)
	}
	b = append(b, ",\"b\":"...)
	b = cfjson.AppendString(b, m.B)
	if m.C != "" {
		b = append(b, ",\"c\":"...)
		b = cfjson.AppendString(b, m.C)
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Mixed) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		switch string(key) {
		case "a":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.A)
		case "b":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.B)
		case "c":
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.String(b, i, f, &m.C)
		default:
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}
