// Code generated by cfjson. DO NOT EDIT.

package fold

import (
	cfjson "github.com/centrifugal/protocol/cfjson"
)

// AppendJSON appends the JSON encoding of m to b.
func (m *Lower) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.Channel != "" {
		b = append(b, ",\"channel\":"...)
		b = cfjson.AppendString(b, m.Channel)
	}
	if m.User != "" {
		b = append(b, ",\"user\":"...)
		b = cfjson.AppendString(b, m.User)
	}
	if m.Info != nil {
		b = append(b, ",\"info\":"...)
		b = m.Info.AppendJSON(b)
	}
	if len(m.Tags) != 0 {
		b = append(b, ",\"tags\":"...)
		s1 := len(b)
		for k2, e3 := range m.Tags {
			b = append(b, ',')
			b = cfjson.AppendString(b, k2)
			b = append(b, ':')
			b = cfjson.AppendString(b, e3)
		}
		b[s1] = '{'
		b = append(b, '}')
	}
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Lower) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	if f += cfjson.DepthStep; f >= cfjson.DepthLimit {
		return ^i
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		folded := false
	match:
		switch string(key) {
		case "channel":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.String(b, i, f, &m.Channel)
		case "user":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.User)
		case "info":
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			if cfjson.IsNull(b, i) {
				m.Info = nil
				i += 4
			} else {
				if m.Info == nil {
					m.Info = new(Lower)
				}
				i = m.Info.DecodeJSON(b, i, f)
			}
		case "tags":
			if seen0&0x8 != 0 {
				return ^i
			}
			seen0 |= 0x8
			if cfjson.IsNull(b, i) {
				m.Tags = nil
				i += 4
			} else {
				if i >= len(b) || b[i] != '{' {
					return ^i
				}
				m.Tags = make(map[string]string)
				i = cfjson.SkipSpace(b, i+1)
				if i < len(b) && b[i] == '}' {
					i++
				} else {
					for {
						var k1 string
						i = cfjson.MapKey(b, i, f, &k1)
						if i < 0 {
							return i
						}
						var e2 string
						i = cfjson.String(b, i, f, &e2)
						if i < 0 {
							return i
						}
						if _, dup := m.Tags[k1]; dup {
							return ^i
						}
						m.Tags[k1] = e2
						i = cfjson.SkipSpace(b, i)
						if i >= len(b) {
							return ^i
						}
						if b[i] == ',' {
							i = cfjson.SkipSpace(b, i+1)
							continue
						}
						if b[i] != '}' {
							return ^i
						}
						i++
						break
					}
				}
			}
		default:
			if !folded {
				folded = true
				if k, ok := cfjson.FoldKey(key); ok {
					key = k
					goto match
				}
			}
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}

// AppendJSON appends the JSON encoding of m to b.
func (m *Mixed) AppendJSON(b []byte) []byte {
	s := len(b)
	if m.NumClients != 0 {
		b = append(b, ",\"numClients\":"...)
		b = cfjson.AppendInt(b, int64(m.NumClients))
	}
	if m.ID != "" {
		b = append(b, ",\"ID\":"...)
		b = cfjson.AppendString(b, m.ID)
	}
	b = append(b, ",\"Untagged\":"...)
	b = cfjson.AppendString(b, m.Untagged)
	if len(b) == s {
		return append(b, '{', '}')
	}
	b[s] = '{'
	return append(b, '}')
}

// DecodeJSON decodes the JSON value at b[i] into m and returns the index after the
// value, or a negative number on error, see cfjson.Error.
func (m *Mixed) DecodeJSON(b []byte, i int, f cfjson.Flags) int {
	if i >= len(b) || b[i] != '{' {
		return cfjson.Null(b, i)
	}
	i = cfjson.SkipSpace(b, i+1)
	if i < len(b) && b[i] == '}' {
		return i + 1
	}
	var seen0 uint64
	for {
		var key []byte
		key, i = cfjson.Key(b, i, f)
		if i < 0 {
			return i
		}
		folded := false
	match:
		switch string(key) {
		case "numClients":
			if seen0&0x1 != 0 {
				return ^i
			}
			seen0 |= 0x1
			i = cfjson.Int(b, i, &m.NumClients)
		case "ID":
			if seen0&0x2 != 0 {
				return ^i
			}
			seen0 |= 0x2
			i = cfjson.String(b, i, f, &m.ID)
		case "Untagged":
			if seen0&0x4 != 0 {
				return ^i
			}
			seen0 |= 0x4
			i = cfjson.String(b, i, f, &m.Untagged)
		default:
			if !folded {
				folded = true
				k, _ := cfjson.FoldKey(key)
				switch string(k) {
				case "numclients":
					key = []byte("numClients")
					goto match
				case "id":
					key = []byte("ID")
					goto match
				case "untagged":
					key = []byte("Untagged")
					goto match
				}
			}
			i = cfjson.Skip(b, i, f)
		}
		if i < 0 {
			return i
		}
		i = cfjson.SkipSpace(b, i)
		if i >= len(b) {
			return ^i
		}
		switch b[i] {
		case ',':
			i = cfjson.SkipSpace(b, i+1)
		case '}':
			return i + 1
		default:
			return ^i
		}
	}
}
